# Generated by Django 5.1.15 on 2026-03-07 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0003_add_department_to_attendancepolicy'),
        ('sales', '0007_alter_coupon_discount_value_alter_refund_approved_by_and_more'),
        ('stores', '0022_add_enterprise_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='telephone')),
                ('vehicle_type', models.CharField(choices=[('MOTO', 'Moto'), ('VOITURE', 'Voiture'), ('VELO', 'Velo'), ('PIETON', 'A pied')], default='MOTO', max_length=20, verbose_name='type de vehicule')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_agent_profile', to='hrm.employee', verbose_name='employe')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agents', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'livreur',
                'verbose_name_plural': 'livreurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PREPARING', 'En preparation'), ('READY', 'Pret'), ('IN_TRANSIT', 'En cours'), ('DELIVERED', 'Livre'), ('RETURNED', 'Retourne'), ('CANCELLED', 'Annule')], db_index=True, default='PENDING', max_length=20, verbose_name='statut')),
                ('delivery_address', models.TextField(verbose_name='adresse de livraison')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='nom du destinataire')),
                ('recipient_phone', models.CharField(max_length=30, verbose_name='telephone du destinataire')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='prevu le')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='recupere le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='livre le')),
                ('confirmation_code', models.CharField(blank=True, default='', max_length=6, verbose_name='code de confirmation')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='sales.sale', verbose_name='vente')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='stores.store', verbose_name='boutique')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.deliveryagent', verbose_name='livreur')),
            ],
            options={
                'verbose_name': 'livraison',
                'verbose_name_plural': 'livraisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=20, verbose_name='ancien statut')),
                ('to_status', models.CharField(max_length=20, verbose_name='nouveau statut')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='raison')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='modifie par')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delivery.delivery', verbose_name='livraison')),
            ],
            options={
                'verbose_name': 'historique statut livraison',
                'verbose_name_plural': 'historiques statut livraison',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='frais de livraison')),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='delai estime (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'zone de livraison',
                'verbose_name_plural': 'zones de livraison',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.deliveryzone', verbose_name='zone'),
        ),
    ]
