# Generated by Django 5.1.15 on 2026-03-08 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('stores', '0023_store_receipt_custom_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMonthlyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7, verbose_name='periode')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='livrees')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='total')),
                ('returned_count', models.PositiveIntegerField(default=0, verbose_name='retournees')),
                ('bonus_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='bonus gagne')),
                ('is_final', models.BooleanField(default=False, verbose_name='mois cloture')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='delivery.deliveryagent', verbose_name='livreur')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_monthly_stats', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'stats mensuelles livreur',
                'verbose_name_plural': 'stats mensuelles livreurs',
                'ordering': ['-period'],
                'unique_together': {('agent', 'period')},
            },
        ),
        migrations.CreateModel(
            name='AgentObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7, verbose_name='periode')),
                ('target_count', models.PositiveIntegerField(verbose_name='objectif livraisons')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='bonus FCFA')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='delivery.deliveryagent', verbose_name='livreur')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_objectives', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'objectif livreur',
                'verbose_name_plural': 'objectifs livreurs',
                'ordering': ['-period'],
                'unique_together': {('agent', 'period')},
            },
        ),
    ]
