# Generated by Django 5.1.15 on 2026-03-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_agent_objectives'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='expenses.expense', verbose_name='depense caisse liee'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant en especes donne a l'agent. Par defaut = zone.fee.", max_digits=12, null=True, verbose_name='montant remis au livreur'),
        ),
    ]
