# Generated by Django 5.1.15 on 2026-03-08 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_delivery_payout'),
        ('stores', '0023_store_receipt_custom_footer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_broadcast',
            field=models.BooleanField(db_index=True, default=False, help_text="True si aucun agent n'a ete selectionne — tous les livreurs peuvent la reclamer.", verbose_name='diffuse a tous les livreurs'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_notes',
            field=models.TextField(blank=True, default='', verbose_name='notes de recuperation'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='createur'),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='compte utilisateur'),
        ),
        migrations.CreateModel(
            name='DeliveryPickupLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='emplacement')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_locations', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'emplacement de recuperation',
                'verbose_name_plural': 'emplacements de recuperation',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.deliverypickuplocation', verbose_name='emplacement de recuperation'),
        ),
    ]
