# Generated by Django 5.1.15 on 2026-03-08 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_broadcast_pickup_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='pickup_code',
            field=models.CharField(blank=True, default='', help_text='Code communique au livreur pour confirmer la recuperation du colis.', max_length=6, verbose_name='code de recuperation'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='recupere le'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='recupere par'),
        ),
    ]
