# Generated by Django 5.2.11 on 2026-03-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_pickup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='collector_name',
            field=models.CharField(blank=True, default='', help_text='Personne qui vient recuperer le colis (si different du destinataire).', max_length=100, verbose_name='nom du recuperateur'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='collector_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='telephone du recuperateur'),
        ),
    ]
