# Generated by Django 5.1.15 on 2026-02-15 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='date')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total ventes')),
                ('total_orders', models.IntegerField(default=0, verbose_name='nombre de commandes')),
                ('average_basket', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='panier moyen')),
                ('gross_margin', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='marge brute')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total remises')),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total remboursements')),
                ('net_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ventes nettes')),
                ('credit_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='encours credit')),
                ('stock_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valeur du stock')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'Snapshot KPI',
                'verbose_name_plural': 'Snapshots KPI',
                'ordering': ['-date'],
                'unique_together': {('store', 'date')},
            },
        ),
    ]
