# Generated by Django 5.1.15 on 2026-02-15 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Entree'), ('OUT', 'Sortie'), ('ADJUST', 'Ajustement'), ('DAMAGE', 'Dommage'), ('TRANSFER_IN', 'Transfert entrant'), ('TRANSFER_OUT', 'Transfert sortant'), ('RETURN', 'Retour'), ('SALE', 'Vente'), ('PURCHASE', 'Achat')], max_length=20, verbose_name='type de mouvement')),
                ('quantity', models.IntegerField(help_text='Positif pour les entrees, negatif pour les sorties.', verbose_name='quantite')),
                ('reference', models.CharField(blank=True, default='', help_text='Numero de vente, bon de commande, etc.', max_length=255, verbose_name='reference')),
                ('reason', models.TextField(blank=True, default='', verbose_name='motif')),
                ('batch_id', models.UUIDField(blank=True, help_text='Regroupe les mouvements lies (ex. transfert).', null=True, verbose_name='identifiant de lot')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='catalog.product', verbose_name='produit')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Termine'), ('CANCELLED', 'Annule')], default='DRAFT', max_length=20, verbose_name='statut')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='termine le')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to=settings.AUTH_USER_MODEL, verbose_name='cree par')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_qty', models.IntegerField(help_text='Quantite en stock au debut du comptage.', verbose_name='quantite systeme')),
                ('counted_qty', models.IntegerField(blank=True, null=True, verbose_name='quantite comptee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_lines', to='catalog.product', verbose_name='produit')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.stockcount', verbose_name='inventaire')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuve'), ('IN_TRANSIT', 'En transit'), ('RECEIVED', 'Recu'), ('CANCELLED', 'Annule')], default='PENDING', max_length=20, verbose_name='statut')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL, verbose_name='approuve par')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_created', to=settings.AUTH_USER_MODEL, verbose_name='cree par')),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='stores.store', verbose_name='boutique source')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='stores.store', verbose_name='boutique destination')),
            ],
            options={
                'verbose_name': 'Transfert de stock',
                'verbose_name_plural': 'Transferts de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='quantite demandee')),
                ('received_qty', models.PositiveIntegerField(default=0, verbose_name='quantite recue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_lines', to='catalog.product', verbose_name='produit')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.stocktransfer', verbose_name='transfert')),
            ],
            options={
                'verbose_name': 'Ligne de transfert',
                'verbose_name_plural': 'Lignes de transfert',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0, verbose_name='quantite en stock')),
                ('reserved_qty', models.IntegerField(default=0, help_text='Quantite reservee pour les ventes partiellement payees.', verbose_name='quantite reservee')),
                ('min_qty', models.IntegerField(default=5, help_text='Seuil minimum de stock avant alerte.', verbose_name='seuil minimum')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='catalog.product', verbose_name='produit')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'Stock produit',
                'verbose_name_plural': 'Stocks produits',
                'ordering': ['product__name'],
                'unique_together': {('store', 'product')},
            },
        ),
    ]
