# Generated by Django 5.1.15 on 2026-02-17 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_enterprise_to_catalog'),
        ('stock', '0001_initial'),
        ('stores', '0010_alter_auditlog_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='catalog.product', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='stores.store', verbose_name='boutique'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='catalog.product', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stocks', to='stores.store', verbose_name='boutique'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Termine'), ('CANCELLED', 'Annule')], db_index=True, default='DRAFT', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='stores.store', verbose_name='boutique'),
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='catalog.product', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='stock_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='stock.stockcount', verbose_name='inventaire'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='from_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='stores.store', verbose_name='boutique source'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuve'), ('IN_TRANSIT', 'En transit'), ('RECEIVED', 'Recu'), ('CANCELLED', 'Annule')], db_index=True, default='PENDING', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='to_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='stores.store', verbose_name='boutique destination'),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='catalog.product', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='stock.stocktransfer', verbose_name='transfert'),
        ),
    ]
