# Generated by Django 5.2.11 on 2026-03-04 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stocklot'),
        ('stores', '0021_alter_enterprise_invoice_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_store', models.F('to_store')), _negated=True), name='ck_transfer_different_stores'),
        ),
    ]
