# Generated by Django 5.2.11 on 2026-03-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stocktransfer_ck_transfer_different_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Regroupe les mouvements lies (ex. transfert).', null=True, verbose_name='identifiant de lot'),
        ),
    ]
