# Generated by Django 5.1.15 on 2026-03-08 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_pricingpolicy_pricingrule_productvariant'),
        ('stock', '0005_alter_inventorymovement_batch_id'),
        ('stores', '0023_store_receipt_custom_footer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productstock',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='catalog.productvariant', verbose_name='variante'),
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('store', 'product', 'variant')},
        ),
    ]
