# Generated by Django 5.1.15 on 2026-02-15 04:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='numero de facture')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_PAYMENT', 'En attente de paiement'), ('PARTIALLY_PAID', 'Partiellement payee'), ('PAID', 'Payee'), ('CANCELLED', 'Annulee'), ('REFUNDED', 'Remboursee')], db_index=True, default='DRAFT', max_length=20, verbose_name='statut')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='sous-total')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='montant remise')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='pourcentage remise')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='montant TVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='montant paye')),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='montant du')),
                ('is_credit_sale', models.BooleanField(default=False, verbose_name='vente a credit')),
                ('reserve_stock', models.BooleanField(default=False, help_text="Reserver le stock lors d'un paiement partiel.", verbose_name='reserver le stock')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Date/heure de soumission au caissier.', null=True, verbose_name='soumise le')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='payee le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulee le')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name="raison d'annulation")),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sales', to=settings.AUTH_USER_MODEL, verbose_name='annulee par')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer', verbose_name='client')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_as_seller', to=settings.AUTH_USER_MODEL, verbose_name='vendeur')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'vente',
                'verbose_name_plural': 'ventes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant')),
                ('reason', models.TextField(verbose_name='raison')),
                ('refund_method', models.CharField(choices=[('CASH', 'Especes'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CREDIT', 'Avoir / Credit')], max_length=20, verbose_name='methode de remboursement')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='reference')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_refunds', to=settings.AUTH_USER_MODEL, verbose_name='approuve par')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='traite par')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='stores.store', verbose_name='boutique')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.sale', verbose_name='vente')),
            ],
            options={
                'verbose_name': 'remboursement',
                'verbose_name_plural': 'remboursements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(help_text='Nom du produit au moment de la vente.', max_length=255, verbose_name='nom produit (snapshot)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix unitaire')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot du cout pour calcul de marge.', max_digits=12, verbose_name='prix de revient')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantite')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='remise ligne')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total ligne')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product', verbose_name='produit')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='vente')),
            ],
            options={
                'verbose_name': 'ligne de vente',
                'verbose_name_plural': 'lignes de vente',
                'ordering': ['created_at'],
            },
        ),
    ]
