# Generated by Django 5.1.15 on 2026-02-17 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_store_to_enterprise'),
        ('sales', '0001_initial'),
        ('stores', '0010_alter_auditlog_entity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='numero de facture'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__isnull', False)), fields=('store', 'invoice_number'), name='uniq_sale_invoice_per_store'),
        ),
    ]
