# Generated by Django 5.1.15 on 2026-02-17 19:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_make_product_category_nullable'),
        ('customers', '0003_customer_is_default'),
        ('sales', '0002_alter_sale_invoice_number_and_more'),
        ('stores', '0012_alter_sequence_unique_together_sequence_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='numero de devis')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoye'), ('ACCEPTED', 'Accepte'), ('REFUSED', 'Refuse'), ('EXPIRED', 'Expire'), ('CONVERTED', 'Converti')], db_index=True, default='DRAFT', max_length=20, verbose_name='statut')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='sous-total')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='montant remise')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='pourcentage remise')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='montant TVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="valide jusqu'au")),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoye le')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepte le')),
                ('refused_at', models.DateTimeField(blank=True, null=True, verbose_name='refuse le')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='converti le')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('conditions', models.TextField(blank=True, default='', verbose_name='conditions particulieres')),
                ('refusal_reason', models.TextField(blank=True, default='', verbose_name='raison du refus')),
                ('converted_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote_obj', to='sales.sale', verbose_name='facture generee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes_created', to=settings.AUTH_USER_MODEL, verbose_name='cree par')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='customers.customer', verbose_name='client')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'devis',
                'verbose_name_plural': 'devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='source_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_sales', to='sales.quote', verbose_name='devis source'),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(help_text='Nom du produit au moment du devis.', max_length=255, verbose_name='nom produit (snapshot)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix unitaire')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot du cout pour calcul de marge.', max_digits=12, verbose_name='prix de revient')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantite')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='remise ligne')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total ligne')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_items', to='catalog.product', verbose_name='produit')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quote', verbose_name='devis')),
            ],
            options={
                'verbose_name': 'ligne de devis',
                'verbose_name_plural': 'lignes de devis',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('quote_number__isnull', False)), fields=('store', 'quote_number'), name='uniq_quote_number_per_store'),
        ),
    ]
