# Generated by Django 5.2.11 on 2026-03-01 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_quote_verification_hash_quote_verification_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='', verbose_name="raison d'annulation"),
        ),
        migrations.AddField(
            model_name='quote',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='annule le'),
        ),
        migrations.AddField(
            model_name='quote',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_quotes', to=settings.AUTH_USER_MODEL, verbose_name='annule par'),
        ),
        migrations.AddField(
            model_name='quote',
            name='document_type',
            field=models.CharField(choices=[('DEVIS', 'Devis'), ('PROFORMA', 'Facture proforma')], db_index=True, default='DEVIS', max_length=20, verbose_name='type de document'),
        ),
        migrations.AddField(
            model_name='refund',
            name='credit_note_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name="numero d'avoir"),
        ),
        migrations.AddField(
            model_name='refund',
            name='restore_stock',
            field=models.BooleanField(default=False, help_text='Remettre les articles en stock lors du remboursement.', verbose_name='remettre en stock'),
        ),
        migrations.AddField(
            model_name='sale',
            name='stock_decremented',
            field=models.BooleanField(default=False, help_text='True si le stock a deja ete decremente pour cette vente.', verbose_name='stock decremente'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoye'), ('ACCEPTED', 'Accepte'), ('REFUSED', 'Refuse'), ('EXPIRED', 'Expire'), ('CONVERTED', 'Converti'), ('CANCELLED', 'Annule')], db_index=True, default='DRAFT', max_length=20, verbose_name='statut'),
        ),
    ]
