# Generated by Django 5.2.11 on 2026-03-03 13:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_quote_cancellation_reason_quote_cancelled_at_and_more'),
        ('stores', '0020_enterprise_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='coupon_code',
            field=models.CharField(blank=True, default='', help_text='Snapshot du code coupon au moment de la vente.', max_length=50, verbose_name='code coupon (snapshot)'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='description')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Pourcentage'), ('FIXED', 'Montant fixe')], default='PERCENT', max_length=10, verbose_name='type de remise')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valeur de remise')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='montant minimum de commande')),
                ('valid_from', models.DateField(verbose_name='valide a partir du')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="valide jusqu'au")),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour un usage illimite.', null=True, verbose_name='utilisations maximum')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name="nombre d'utilisations")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'code')},
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_sales', to='sales.coupon', verbose_name='coupon'),
        ),
    ]
