# Generated by Django 5.1.15 on 2026-03-08 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_pricingpolicy_pricingrule_productvariant'),
        ('customers', '0006_customer_last_purchase_at_customer_loyalty_score_and_more'),
        ('sales', '0007_alter_coupon_discount_value_alter_refund_approved_by_and_more'),
        ('stores', '0023_store_receipt_custom_footer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='inspection_notes',
            field=models.TextField(blank=True, default='', verbose_name="notes d'inspection"),
        ),
        migrations.AddField(
            model_name='refund',
            name='is_abnormal',
            field=models.BooleanField(default=False, help_text='Flagge par le systeme comme taux de retour anormal.', verbose_name='anormal'),
        ),
        migrations.AddField(
            model_name='refund',
            name='physical_return',
            field=models.BooleanField(default=False, help_text='Le produit a ete physiquement rendu.', verbose_name='retour physique'),
        ),
        migrations.AddField(
            model_name='refund',
            name='return_reason_code',
            field=models.CharField(choices=[('DEFECT', 'Defaut / produit defectueux'), ('WRONG_ITEM', 'Mauvais article'), ('CHANGED_MIND', "Changement d'avis"), ('NOT_AS_DESCRIBED', 'Non conforme a la description'), ('DAMAGED_DELIVERY', 'Endommage a la livraison'), ('OTHER', 'Autre')], default='OTHER', max_length=30, verbose_name='code motif'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='catalog.productvariant', verbose_name='variante'),
        ),
        migrations.CreateModel(
            name='RecurringSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('frequency', models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel')], max_length=10, verbose_name='frequence')),
                ('frequency_day', models.IntegerField(blank=True, help_text='1=Lundi si WEEKLY, 1-28 si MONTHLY, ignore si DAILY.', null=True, verbose_name='jour de declenchement')),
                ('next_due_date', models.DateField(db_index=True, verbose_name='prochaine echeance')),
                ('last_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='derniere generation')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('auto_submit', models.BooleanField(default=False, help_text='Si True: cree en PENDING_PAYMENT, sinon DRAFT.', verbose_name='soumettre automatiquement')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_sales', to='customers.customer', verbose_name='client')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_sales', to=settings.AUTH_USER_MODEL, verbose_name='vendeur')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_sales', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'Vente recurrente',
                'verbose_name_plural': 'Ventes recurrentes',
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantite')),
                ('unit_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour utiliser le prix catalogue.', max_digits=12, null=True, verbose_name='prix unitaire specifique')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_sale_items', to='catalog.product', verbose_name='produit')),
                ('recurring_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.recurringsale', verbose_name='vente recurrente')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_sale_items', to='catalog.productvariant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'Article vente recurrente',
                'verbose_name_plural': 'Articles ventes recurrentes',
            },
        ),
    ]
