# Generated by Django 5.1.15 on 2026-03-08 15:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_refund_inspection_notes_refund_is_abnormal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='frais de livraison'),
        ),
    ]
