# Generated by Django 5.1.15 on 2026-02-17 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_supplier_store_to_enterprise'),
        ('stores', '0010_alter_auditlog_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceipt',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchases.goodsreceipt'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('PARTIALLY_RECEIVED', 'Partiellement recu'), ('RECEIVED', 'Recu'), ('CANCELLED', 'Annule')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchases.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='stores.enterprise'),
        ),
    ]
