# Generated by Django 5.1.15 on 2026-02-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bank_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='invoice_footer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='invoice_header',
            field=models.CharField(blank=True, default='FACTURE', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='invoice_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
