# Generated by Django 5.1.15 on 2026-02-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_bank_details_store_invoice_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='invoice_template',
            field=models.CharField(choices=[('CLASSIC', 'Classique'), ('MODERN', 'Moderne')], default='CLASSIC', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/logos/'),
        ),
    ]
