# Generated by Django 5.1.15 on 2026-02-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_invoice_template_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='invoice_primary_color',
            field=models.CharField(default='#0F4C9A', max_length=7),
        ),
        migrations.AddField(
            model_name='store',
            name='invoice_secondary_color',
            field=models.CharField(default='#21A8F6', max_length=7),
        ),
        migrations.AddField(
            model_name='store',
            name='offer_validity_days',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
