# Generated by Django 5.1.15 on 2026-02-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_invoice_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='vat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AlterField(
            model_name='store',
            name='invoice_template',
            field=models.CharField(choices=[('CLASSIC', 'Classique'), ('MODERN', 'Moderne'), ('SIMPLE', 'Simple')], default='CLASSIC', max_length=20),
        ),
    ]
