# Generated by Django 5.1.15 on 2026-02-15 20:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_vat_enabled_store_vat_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('legal_name', models.CharField(blank=True, default='', max_length=255, verbose_name='raison sociale')),
                ('registration_number', models.CharField(blank=True, default='', max_length=100, verbose_name='numero RCCM')),
                ('tax_id', models.CharField(blank=True, default='', max_length=100, verbose_name='numero contribuable')),
                ('currency', models.CharField(default='FCFA', max_length=10, verbose_name='devise')),
                ('vat_enabled', models.BooleanField(default=False, verbose_name='TVA activee')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('19.25'), max_digits=5, verbose_name='taux TVA (%)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='enterprises/logos/', verbose_name='logo')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='telephone')),
                ('website', models.URLField(blank=True, default='', verbose_name='site web')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='store',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='stores.enterprise', verbose_name='entreprise'),
        ),
    ]
