# Generated by Django 5.1.15 on 2026-02-15 20:33

from django.db import migrations


def create_default_enterprise(apps, schema_editor):
    """Create a default Enterprise from the first existing Store and link all stores."""
    Enterprise = apps.get_model("stores", "Enterprise")
    Store = apps.get_model("stores", "Store")

    first_store = Store.objects.first()
    if not first_store:
        # No stores exist yet; nothing to migrate.
        return

    enterprise = Enterprise.objects.create(
        name=first_store.legal_name or first_store.name,
        code="ENT-001",
        legal_name=first_store.legal_name,
        registration_number=first_store.registration_number,
        tax_id=first_store.tax_id,
        currency=first_store.currency,
        vat_enabled=first_store.vat_enabled,
        vat_rate=first_store.vat_rate,
        email=first_store.email,
        phone=first_store.phone,
    )

    Store.objects.all().update(enterprise=enterprise)


def reverse_migration(apps, schema_editor):
    """Remove all Enterprise records (stores keep their data intact)."""
    Enterprise = apps.get_model("stores", "Enterprise")
    Enterprise.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0006_create_enterprise_model"),
    ]

    operations = [
        migrations.RunPython(create_default_enterprise, reverse_migration),
    ]
