# Generated by Django 5.1.15 on 2026-02-15 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_populate_default_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='stores.enterprise', verbose_name='entreprise'),
        ),
    ]
