# Generated by Django 5.1.15 on 2026-02-16
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0008_store_enterprise_non_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="analytics_feature_flags",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Activation des briques analytics au niveau entreprise.",
                verbose_name="flags analytics",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="analytics_feature_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Overrides boutique des flags analytics (true/false).",
                verbose_name="surcharges flags analytics",
            ),
        ),
    ]

