# Generated by Django 5.1.15 on 2026-02-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_alter_auditlog_entity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='bank_details',
            field=models.TextField(blank=True, default='', verbose_name='coordonnees bancaires'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='invoice_footer',
            field=models.TextField(blank=True, default='', verbose_name='pied de page facture'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='invoice_header',
            field=models.CharField(blank=True, default='FACTURE', max_length=100, verbose_name='titre facture'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='invoice_primary_color',
            field=models.CharField(default='#0F4C9A', max_length=7, verbose_name='couleur primaire'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='invoice_secondary_color',
            field=models.CharField(default='#21A8F6', max_length=7, verbose_name='couleur secondaire'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='invoice_template',
            field=models.CharField(choices=[('CLASSIC', 'Classique'), ('MODERN', 'Moderne'), ('SIMPLE', 'Simple')], default='CLASSIC', max_length=20, verbose_name='modele facture'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='invoice_terms',
            field=models.TextField(blank=True, default='', verbose_name='conditions facture'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='offer_validity_days',
            field=models.PositiveIntegerField(default=15, verbose_name='validite devis (jours)'),
        ),
    ]
