# Generated by Django 5.1.15 on 2026-02-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_add_invoice_fields_to_enterprise'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sequence',
            name='year',
            field=models.PositiveIntegerField(default=2026, help_text='Year for this sequence (allows per-year numbering).', verbose_name='annee'),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together={('store', 'prefix', 'year')},
        ),
    ]
