# Generated by Django 5.1.15 on 2026-02-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_alter_sequence_unique_together_sequence_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, help_text='Liste des capacites explicites. Vide = fallback sur le role.', verbose_name='capacites'),
        ),
    ]
