# Generated by Django 5.1.15 on 2026-02-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_add_capabilities_to_storeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='can_create_stores',
            field=models.BooleanField(default=True, help_text="Si True, l'admin de l'entreprise peut creer de nouvelles boutiques.", verbose_name='peut creer des boutiques'),
        ),
    ]
