# Generated by Django 5.2.11 on 2026-02-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_add_can_create_stores_to_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='subscription_end',
            field=models.DateField(blank=True, help_text="Date d'expiration. Vide = pas d'expiration.", null=True, verbose_name="fin d'abonnement"),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='subscription_start',
            field=models.DateField(blank=True, help_text="Date de debut de l'abonnement. Vide = actif immediatement.", null=True, verbose_name="debut d'abonnement"),
        ),
    ]
