# Generated by Django 5.1.15 on 2026-02-23 01:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_enterprise_subscription_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_code', models.CharField(default='STANDARD', max_length=50, verbose_name='code plan')),
                ('plan_name', models.CharField(default='Plan Standard', max_length=100, verbose_name='nom plan')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('QUARTERLY', 'Trimestriel'), ('YEARLY', 'Annuel'), ('CUSTOM', 'Personnalise')], default='MONTHLY', max_length=20, verbose_name='cycle de facturation')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='montant')),
                ('currency', models.CharField(default='FCFA', max_length=10, verbose_name='devise')),
                ('starts_on', models.DateField(verbose_name='debut')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('status', models.CharField(choices=[('TRIAL', 'Essai'), ('ACTIVE', 'Actif'), ('PAST_DUE', 'Impayee'), ('CANCELED', 'Resilie'), ('EXPIRED', 'Expire')], default='ACTIVE', max_length=20, verbose_name='statut')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='renouvellement auto')),
                ('external_subscription_id', models.CharField(blank=True, default='', max_length=120, verbose_name='identifiant abonnement externe')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadonnees')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='stores.enterprise', verbose_name='entreprise')),
            ],
            options={
                'verbose_name': 'Abonnement entreprise',
                'verbose_name_plural': 'Abonnements entreprise',
                'ordering': ['-starts_on', '-created_at'],
                'indexes': [models.Index(fields=['enterprise', 'status'], name='sub_ent_status_idx'), models.Index(fields=['ends_on'], name='sub_ends_on_idx')],
            },
        ),
    ]
