# Generated by Django 5.1.15 on 2026-02-25 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_enterprisesubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code module')),
                ('name', models.CharField(max_length=120, verbose_name='nom module')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('display_order', models.PositiveIntegerField(default=100, verbose_name='ordre affichage')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'Module payant',
                'verbose_name_plural': 'Modules payants',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='billing_module_active_idx'), models.Index(fields=['display_order'], name='billing_module_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code plan')),
                ('name', models.CharField(max_length=120, verbose_name='nom plan')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('QUARTERLY', 'Trimestriel'), ('YEARLY', 'Annuel'), ('CUSTOM', 'Personnalise')], default='MONTHLY', max_length=20, verbose_name='cycle facturation')),
                ('base_price_fcfa', models.BigIntegerField(default=0, verbose_name='prix de base FCFA')),
                ('currency', models.CharField(default='FCFA', max_length=10, verbose_name='devise')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'Plan commercial',
                'verbose_name_plural': 'Plans commerciaux',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='billing_plan_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillingModuleDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='stores.billingmodule', verbose_name='dependance')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='stores.billingmodule', verbose_name='module')),
            ],
            options={
                'verbose_name': 'Dependance module',
                'verbose_name_plural': 'Dependances modules',
                'constraints': [models.UniqueConstraint(fields=('module', 'depends_on_module'), name='uniq_module_dependency'), models.CheckConstraint(condition=models.Q(('module', models.F('depends_on_module')), _negated=True), name='chk_module_dependency_not_self')],
            },
        ),
        migrations.CreateModel(
            name='BillingPlanModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('included', models.BooleanField(default=True, verbose_name='inclus')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_links', to='stores.billingmodule', verbose_name='module')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='stores.billingplan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'Module du plan',
                'verbose_name_plural': 'Modules des plans',
                'constraints': [models.UniqueConstraint(fields=('plan', 'module'), name='uniq_plan_module')],
            },
        ),
        migrations.CreateModel(
            name='EnterprisePlanAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('TRIAL', 'Essai'), ('ACTIVE', 'Actif'), ('PAST_DUE', 'Impaye'), ('CANCELED', 'Resilie'), ('EXPIRED', 'Expire')], default='ACTIVE', max_length=20, verbose_name='statut')),
                ('starts_on', models.DateField(verbose_name='debut')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='renouvellement auto')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assignments', to='stores.enterprise', verbose_name='entreprise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enterprise_assignments', to='stores.billingplan', verbose_name='plan')),
                ('source_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_assignments', to='stores.enterprisesubscription', verbose_name='abonnement source')),
            ],
            options={
                'verbose_name': 'Affectation plan entreprise',
                'verbose_name_plural': 'Affectations plans entreprise',
                'ordering': ['-starts_on', '-created_at'],
                'indexes': [models.Index(fields=['enterprise', 'status'], name='ent_plan_status_idx'), models.Index(fields=['starts_on', 'ends_on'], name='ent_plan_window_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreModuleEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('INHERIT', 'Heriter'), ('ENABLED', 'Activer'), ('DISABLED', 'Desactiver')], default='INHERIT', max_length=20, verbose_name='etat')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='raison')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_module_entitlements', to=settings.AUTH_USER_MODEL, verbose_name='cree par')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_entitlements', to='stores.billingmodule', verbose_name='module')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_entitlements', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'Entitlement module boutique',
                'verbose_name_plural': 'Entitlements modules boutiques',
                'ordering': ['store', 'module__display_order', 'module__name'],
                'indexes': [models.Index(fields=['store', 'state'], name='store_module_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'module'), name='uniq_store_module_entitlement')],
            },
        ),
    ]
