# Generated by Django 5.2.11 on 2026-03-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_billingmodule_billingplan_billingmoduledependency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='allow_negative_stock',
            field=models.BooleanField(default=False, help_text='Permet de vendre meme si le stock affiche est insuffisant.', verbose_name='autoriser stock negatif'),
        ),
        migrations.AddField(
            model_name='store',
            name='stock_decrement_on',
            field=models.CharField(choices=[('PAYMENT', 'Au paiement complet'), ('VALIDATION', 'A la validation (soumission)')], default='PAYMENT', help_text='Quand decrementer le stock: au paiement complet ou a la soumission en caisse.', max_length=20, verbose_name='decrement stock a'),
        ),
    ]
