# Generated by Django 5.2.11 on 2026-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_store_allow_negative_stock_store_stock_decrement_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('SARL', 'SARL'), ('SA', 'SA'), ('SAS', 'SAS'), ('SNC', 'SNC'), ('SCS', 'SCS'), ('GIE', 'GIE'), ('EI', 'Entreprise individuelle'), ('AUTRE', 'Autre')], default='', max_length=20, verbose_name='forme juridique'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='share_capital',
            field=models.CharField(blank=True, default='', help_text='Ex: 1 000 000 FCFA', max_length=100, verbose_name='capital social'),
        ),
    ]
