# Generated by Django 5.2.11 on 2026-03-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_enterprise_legal_form_share_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='adresse'),
        ),
    ]
