# Generated by Django 5.2.11 on 2026-03-04 19:15

import stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_enterprise_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='invoice_template',
            field=models.CharField(choices=[('CLASSIC', 'Classique'), ('MODERN', 'Moderne'), ('SIMPLE', 'Simple'), ('CORPORATE', 'Corporate'), ('BORDERED', 'Structuré'), ('PRESTIGE', 'Prestige')], default='CLASSIC', max_length=20, verbose_name='modele facture'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='year',
            field=models.PositiveIntegerField(default=stores.models._current_year, help_text='Year for this sequence (allows per-year numbering).', verbose_name='annee'),
        ),
        migrations.AlterField(
            model_name='store',
            name='invoice_template',
            field=models.CharField(choices=[('CLASSIC', 'Classique'), ('MODERN', 'Moderne'), ('SIMPLE', 'Simple'), ('CORPORATE', 'Corporate'), ('BORDERED', 'Structuré'), ('PRESTIGE', 'Prestige')], default='CLASSIC', max_length=20),
        ),
    ]
