# Generated by Django 5.2.11 on 2026-03-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_alter_enterprise_invoice_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='timezone',
            field=models.CharField(default='Africa/Ouagadougou', help_text="Fuseau horaire de l'entreprise (ex: Africa/Ouagadougou, Europe/Paris).", max_length=50, verbose_name='fuseau horaire'),
        ),
    ]
