# Generated by Django 5.1.15 on 2026-03-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0022_add_enterprise_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='receipt_custom_footer',
            field=models.TextField(blank=True, default='', help_text="Jusqu'a 3 lignes libres affichees en bas du ticket.", verbose_name='pied de page ticket personnalise'),
        ),
        migrations.AddField(
            model_name='store',
            name='receipt_promo_message',
            field=models.CharField(blank=True, default='', help_text='Ex: Merci de votre visite ! Revenez vite.', max_length=200, verbose_name='message promotionnel ticket'),
        ),
        migrations.AddField(
            model_name='store',
            name='receipt_show_loyalty_points',
            field=models.BooleanField(default=False, verbose_name='afficher points fidelite sur ticket'),
        ),
    ]
