# Generated by Django 5.1.15 on 2026-02-15 04:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'marque',
                'verbose_name_plural': 'marques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='categorie parente')),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('sku', models.CharField(help_text='Reference interne unique du produit.', max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='code-barres')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="prix d'achat")),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix de vente')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='marque')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='categorie')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/', verbose_name='image')),
                ('is_primary', models.BooleanField(default=False, verbose_name='image principale')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ordre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'image produit',
                'verbose_name_plural': 'images produit',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Ex: "RAM", "Stockage"', max_length=100, verbose_name='cle')),
                ('value', models.CharField(max_length=255, verbose_name='valeur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'specification produit',
                'verbose_name_plural': 'specifications produit',
                'ordering': ['key'],
                'unique_together': {('product', 'key')},
            },
        ),
    ]
