# Generated by Django 5.1.15 on 2026-02-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_make_product_category_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PRODUCT', 'Produit'), ('SERVICE', 'Service')], db_index=True, default='PRODUCT', max_length=20, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True, help_text='Desactive automatiquement pour les services.', verbose_name='suivi du stock'),
        ),
    ]
