# Generated by Django 5.1.15 on 2026-03-08 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_is_active_alter_product_sku'),
        ('stores', '0023_store_receipt_custom_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Plus la valeur est elevee, plus la politique est appliquee en premier.', verbose_name='priorite')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valable du')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="valable jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('customer_tier', models.CharField(blank=True, choices=[('BRONZE', 'Bronze'), ('SILVER', 'Argent'), ('GOLD', 'Or'), ('PLATINUM', 'Platine')], help_text='Laisser vide pour appliquer a tous les niveaux.', max_length=10, null=True, verbose_name='niveau client')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_policies', to='stores.enterprise', verbose_name='entreprise')),
                ('store', models.ForeignKey(blank=True, help_text='Laisser vide pour appliquer a toutes les boutiques.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_policies', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'Politique de prix',
                'verbose_name_plural': 'Politiques de prix',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_qty', models.PositiveIntegerField(default=1, help_text='Quantite minimale pour declencher la remise volume.', verbose_name='quantite minimum')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Pourcentage'), ('FIXED', 'Montant fixe'), ('FIXED_PRICE', 'Prix fixe')], max_length=15, verbose_name='type de remise')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='%, montant fixe ou prix final selon le type.', max_digits=12, verbose_name='valeur remise')),
                ('category', models.ForeignKey(blank=True, help_text='Appliquer a toute une categorie si produit non specifie.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='catalog.category', verbose_name='categorie')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='catalog.pricingpolicy', verbose_name='politique')),
                ('product', models.ForeignKey(blank=True, help_text='Laisser vide pour appliquer a tous les produits.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='catalog.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'Regle de prix',
                'verbose_name_plural': 'Regles de prix',
                'ordering': ['-min_qty'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Ex: "Rouge / L", "Bleu / XL", "500g"', max_length=100, verbose_name='nom de la variante')),
                ('sku', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='SKU variante')),
                ('barcode', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='code-barres')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Laisse vide pour utiliser le prix du produit parent.', max_digits=12, null=True, verbose_name="prix d'achat")),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Laisse vide pour utiliser le prix du produit parent.', max_digits=12, null=True, verbose_name='prix de vente')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'variante produit',
                'verbose_name_plural': 'variantes produit',
                'ordering': ['name'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
