# Generated by Django 5.2.11 on 2026-03-01 19:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0018_store_allow_negative_stock_store_stock_decrement_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='code comptable')),
                ('name', models.CharField(max_length=255, verbose_name='libelle')),
                ('account_type', models.CharField(choices=[('ASSET', 'Actif'), ('LIABILITY', 'Passif'), ('EQUITY', 'Capitaux propres'), ('INCOME', 'Produit'), ('EXPENSE', 'Charge')], db_index=True, max_length=20, verbose_name='type de compte')),
                ('is_system', models.BooleanField(default=False, help_text='Les comptes systeme ne peuvent pas etre supprimes.', verbose_name='compte systeme')),
                ('allow_entries', models.BooleanField(default=True, help_text='Seuls les comptes feuilles acceptent les ecritures.', verbose_name='accepte les ecritures')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='stores.enterprise', verbose_name='entreprise')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account', verbose_name='compte parent')),
            ],
            options={
                'verbose_name': 'compte comptable',
                'verbose_name_plural': 'comptes comptables',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='libelle')),
                ('start_date', models.DateField(verbose_name='date de debut')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('CLOSED', 'Cloture')], db_index=True, default='OPEN', max_length=10, verbose_name='statut')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='cloture le')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cloture par')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_years', to='stores.enterprise', verbose_name='entreprise')),
            ],
            options={
                'verbose_name': 'exercice fiscal',
                'verbose_name_plural': 'exercices fiscaux',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_number', models.PositiveIntegerField(help_text='0=ouverture, 1-12=mois, 13=cloture', verbose_name='numero de periode')),
                ('start_date', models.DateField(verbose_name='date de debut')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('CLOSED', 'Cloture')], db_index=True, default='OPEN', max_length=10, verbose_name='statut')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear', verbose_name='exercice fiscal')),
            ],
            options={
                'verbose_name': 'periode comptable',
                'verbose_name_plural': 'periodes comptables',
                'ordering': ['fiscal_year', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='libelle')),
                ('journal_type', models.CharField(choices=[('VE', 'Ventes'), ('AC', 'Achats'), ('CA', 'Caisse'), ('BQ', 'Banque'), ('MM', 'Mobile Money'), ('OD', 'Operations Diverses'), ('AN', 'A-Nouveaux')], db_index=True, max_length=5, verbose_name='type de journal')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('default_credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte credit par defaut')),
                ('default_debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte debit par defaut')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='stores.enterprise', verbose_name='entreprise')),
            ],
            options={
                'verbose_name': 'journal comptable',
                'verbose_name_plural': 'journaux comptables',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField(help_text='Numerotation continue par journal et exercice.', verbose_name='numero de sequence')),
                ('entry_date', models.DateField(db_index=True, verbose_name="date de l'ecriture")),
                ('label', models.CharField(max_length=255, verbose_name='libelle')),
                ('reference', models.CharField(blank=True, default='', help_text='Numero de facture, avoir, etc.', max_length=100, verbose_name='reference')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validee'), ('POSTED', 'Comptabilisee')], db_index=True, default='DRAFT', max_length=15, verbose_name='statut')),
                ('source_type', models.CharField(blank=True, default='', help_text='sale, payment, refund, purchase, expense, credit_payment', max_length=50, verbose_name='type source')),
                ('source_id', models.UUIDField(blank=True, help_text="ID de l'objet metier source.", null=True, verbose_name='ID source')),
                ('is_reversal', models.BooleanField(default=False, verbose_name='contre-passation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='cree par')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='stores.enterprise', verbose_name='entreprise')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.fiscalyear', verbose_name='exercice fiscal')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.journal', verbose_name='journal')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.accountingperiod', verbose_name='periode')),
                ('reversed_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='accounting.journalentry', verbose_name='ecriture contre-passee')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='stores.store', verbose_name='boutique')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='valide par')),
            ],
            options={
                'verbose_name': 'ecriture comptable',
                'verbose_name_plural': 'ecritures comptables',
                'ordering': ['-entry_date', '-sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='debit')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='credit')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='libelle')),
                ('partner_type', models.CharField(blank=True, default='', help_text='customer ou supplier', max_length=20, verbose_name='type partenaire')),
                ('partner_id', models.UUIDField(blank=True, null=True, verbose_name='ID partenaire')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_lines', to='accounting.account', verbose_name='compte')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='ecriture')),
            ],
            options={
                'verbose_name': "ligne d'ecriture",
                'verbose_name_plural': "lignes d'ecriture",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='libelle')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Taux en pourcentage (ex: 19.25).', max_digits=5, verbose_name='taux (%)')),
                ('is_exempt', models.BooleanField(default=False, help_text="Si coche, aucune TVA n'est appliquee.", verbose_name='exonere')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('collected_account', models.ForeignKey(blank=True, help_text='Compte 4431 par defaut.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte TVA collectee')),
                ('deductible_account', models.ForeignKey(blank=True, help_text='Compte 4451 par defaut.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte TVA deductible')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='stores.enterprise', verbose_name='entreprise')),
            ],
            options={
                'verbose_name': 'taux de taxe',
                'verbose_name_plural': 'taux de taxes',
                'ordering': ['rate'],
            },
        ),
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_post_entries', models.BooleanField(default=True, help_text='Si active, les ecritures automatiques passent directement en statut POSTED.', verbose_name='comptabiliser automatiquement')),
                ('default_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte banque (521)')),
                ('default_cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte caisse (571)')),
                ('default_customer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte clients (411)')),
                ('default_discount_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte remises (673)')),
                ('default_mobile_money_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte mobile money (585)')),
                ('default_other_income_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte autres produits (706)')),
                ('default_purchase_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte achats (601)')),
                ('default_refund_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte RRR accordes (709)')),
                ('default_sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte ventes (701)')),
                ('default_stock_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte stocks (31)')),
                ('default_stock_variation_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte variation stocks (6031)')),
                ('default_supplier_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte fournisseurs (401)')),
                ('default_vat_collected_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte TVA collectee (4431)')),
                ('default_vat_deductible_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='compte TVA deductible (4451)')),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_settings', to='stores.enterprise', verbose_name='entreprise')),
                ('default_tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.taxrate', verbose_name='taux de taxe par defaut')),
            ],
            options={
                'verbose_name': 'parametres comptables',
                'verbose_name_plural': 'parametres comptables',
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('enterprise', 'code'), name='unique_account_code_per_enterprise'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('fiscal_year', 'period_number'), name='unique_period_per_fiscal_year'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('enterprise', 'code'), name='unique_journal_code_per_enterprise'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('journal', 'fiscal_year', 'sequence_number'), name='unique_sequence_per_journal_year'),
        ),
    ]
