# Generated by Django 5.1.15 on 2026-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de validation'),
        ),
    ]
