# Generated by Django 5.1.15 on 2026-02-15 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('CLOSED', 'Ferme')], default='OPEN', max_length=10, verbose_name='statut')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='ouvert le')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='ferme le')),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, help_text='Montant en caisse au debut de la session.', max_digits=14, verbose_name='fond de caisse initial')),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, help_text='Montant calcule attendu en caisse.', max_digits=14, verbose_name='especes attendues')),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Montant reel compte en caisse a la fermeture.', max_digits=14, null=True, verbose_name='especes comptees')),
                ('variance', models.DecimalField(blank=True, decimal_places=2, help_text='Difference entre especes comptees et especes attendues.', max_digits=14, null=True, verbose_name='ecart')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total ventes')),
                ('total_cash_payments', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total paiements especes')),
                ('total_mobile_payments', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total paiements mobile')),
                ('total_bank_payments', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total paiements bancaires')),
                ('total_credit_payments', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total paiements a credit')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shifts', to=settings.AUTH_USER_MODEL, verbose_name='caissier')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shifts', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CASH', 'Especes'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CREDIT', 'Credit'), ('CHEQUE', 'Cheque')], max_length=20, verbose_name='methode de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant')),
                ('reference', models.CharField(blank=True, default='', help_text='Reference Mobile Money, numero de virement, etc.', max_length=100, verbose_name='reference')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_processed', to=settings.AUTH_USER_MODEL, verbose_name='caissier')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='vente')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cashier.cashshift', verbose_name='session de caisse')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
