# Generated by Django 5.1.15 on 2026-02-17 00:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
        ('sales', '0001_initial'),
        ('stores', '0010_alter_auditlog_entity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashshift',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to=settings.AUTH_USER_MODEL, verbose_name='caissier'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='closing_cash',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant reel compte en caisse a la fermeture.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='especes comptees'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='expected_cash',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant calcule attendu en caisse.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='especes attendues'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='opening_float',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant en caisse au debut de la session.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='fond de caisse initial'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ouvert'), ('CLOSED', 'Ferme')], db_index=True, default='OPEN', max_length=10, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to='stores.store', verbose_name='boutique'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='total_bank_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total paiements bancaires'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='total_cash_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total paiements especes'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='total_credit_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total paiements a credit'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='total_mobile_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total paiements mobile'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total ventes'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='montant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_processed', to=settings.AUTH_USER_MODEL, verbose_name='caissier'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale', verbose_name='vente'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cashier.cashshift', verbose_name='session de caisse'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='stores.store', verbose_name='boutique'),
        ),
    ]
