# Generated by Django 5.2.11 on 2026-03-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_alter_cashshift_cashier_alter_cashshift_closing_cash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashshift',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ouvert le'),
        ),
    ]
