# Generated by Django 5.1.15 on 2026-03-08 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_alter_cashshift_opened_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShiftDenomination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('denomination', models.PositiveIntegerField(help_text='Valeur faciale en FCFA (ex: 10000, 5000, 1000, 500...).', verbose_name='coupure')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='nombre')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='cashier.cashshift', verbose_name='session de caisse')),
            ],
            options={
                'verbose_name': 'Coupure de caisse',
                'verbose_name_plural': 'Coupures de caisse',
                'ordering': ['-denomination'],
                'unique_together': {('shift', 'denomination')},
            },
        ),
    ]
