# Generated by Django 5.1.15 on 2026-03-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashshift',
            name='total_bank_refunds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total remboursements bancaires'),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='total_cash_refunds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total remboursements especes'),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='total_mobile_refunds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total remboursements mobile'),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='total_refunds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total remboursements'),
        ),
    ]
