# Generated by Django 5.1.15 on 2026-02-15 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='prenom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='telephone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail')),
                ('address', models.TextField(blank=True, default='', verbose_name='adresse')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='entreprise')),
                ('tax_id', models.CharField(blank=True, default='', max_length=50, verbose_name='numero fiscal')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
