# Generated by Django 5.1.15 on 2026-02-17

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_store_to_enterprise"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_default",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Client generique utilise quand aucun client n'est selectionne (ex: Client comptant).",
                verbose_name="client par defaut",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=Q(("is_default", True)),
                fields=("enterprise",),
                name="uniq_default_customer_per_enterprise",
            ),
        ),
    ]

