# Generated by Django 5.2.11 on 2026-03-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254, verbose_name='e-mail'),
        ),
    ]
