# Generated by Django 5.1.15 on 2026-03-08 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_email'),
        ('sales', '0007_alter_coupon_discount_value_alter_refund_approved_by_and_more'),
        ('stores', '0023_store_receipt_custom_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_purchase_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernier achat'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='score fidelite'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_tier',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Argent'), ('GOLD', 'Or'), ('PLATINUM', 'Platine')], default='BRONZE', max_length=10, verbose_name='niveau fidelite'),
        ),
        migrations.AddField(
            model_name='customer',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, verbose_name="nombre d'achats"),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total achats'),
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='solde points')),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='points gagnes (total)')),
                ('points_redeemed', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='points utilises (total)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_accounts', to='customers.customer', verbose_name='client')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_accounts', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'Compte fidelite',
                'verbose_name_plural': 'Comptes fidelite',
                'unique_together': {('store', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('EARN', 'Gain'), ('REDEEM', 'Utilisation'), ('ADJUST', 'Ajustement'), ('EXPIRE', 'Expiration')], max_length=10, verbose_name='type')),
                ('points', models.DecimalField(decimal_places=2, help_text='Positif=gagnes, negatif=utilises/expires.', max_digits=12, verbose_name='points')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='solde apres')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='reference')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.loyaltyaccount', verbose_name='compte fidelite')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='sales.sale', verbose_name='vente')),
            ],
            options={
                'verbose_name': 'Transaction fidelite',
                'verbose_name_plural': 'Transactions fidelite',
                'ordering': ['-created_at'],
            },
        ),
    ]
