# Generated by Django 5.1.15 on 2026-02-26 12:32

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_customer_created_by'),
        ('sales', '0003_quote_sale_source_quote_quoteitem_and_more'),
        ('stores', '0017_billingmodule_billingplan_billingmoduledependency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('VISIT', 'Visit'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('NOTE', 'Note'), ('MEETING', 'Meeting')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('INTERESTED', 'Interested'), ('NEUTRAL', 'Neutral'), ('NO_ANSWER', 'No answer'), ('BLOCKED', 'Blocked')], default='NEUTRAL', max_length=20)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_activities_logged', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_activities', to='stores.store')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CommercialActivityAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='commercial/activities/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='commercial.commercialactivity')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.CharField(max_length=255)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('report_file', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_import_jobs_started', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_import_jobs', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialImportErrorRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows_detail', to='commercial.commercialimportjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialIncentivePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('STORE', 'Store')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_margin_pct_for_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_incentive_policies', to='stores.enterprise')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_incentive_policies', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialIncentiveRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=12)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_incentive_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_incentive_runs_computed', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='commercial.commercialincentivepolicy')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_incentive_runs', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialIncentiveResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('quoted_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('meeting_count', models.PositiveIntegerField(default=0)),
                ('avg_margin_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tier_name', models.CharField(blank=True, default='', max_length=60)),
                ('base_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('objective_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('margin_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('final_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('explain_json', models.JSONField(blank=True, default=dict)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_incentive_results', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='commercial.commercialincentiverun')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialIncentiveTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=60)),
                ('min_signed_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_signed_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fixed_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('variable_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='commercial.commercialincentivepolicy')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='CommercialLeadSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('MANUAL', 'Manual'), ('FORM', 'Form'), ('CSV', 'CSV import'), ('API', 'API')], max_length=20)),
                ('label', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_lead_sources', to='stores.enterprise')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='CommercialObjectiveMonthly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7)),
                ('target_signed_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('target_quoted_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('target_win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('target_meetings', models.PositiveIntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_objectives', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_objectives', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('PROSPECT', 'Prospect'), ('CONTACTED', 'Contacted'), ('RDV', 'Meeting'), ('QUOTE_SENT', 'Quote sent'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='PROSPECT', max_length=20)),
                ('probability_pct', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estimated_margin_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('expected_close_date', models.DateField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, default='', max_length=180)),
                ('lost_comment', models.TextField(blank=True, default='')),
                ('pipeline_order', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_opportunities_owned', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_opportunities', to='sales.quote')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_opportunities', to='stores.store')),
                ('won_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_opportunities', to='sales.sale')),
            ],
            options={
                'ordering': ['stage', 'pipeline_order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommercialAISignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_type', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warn'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('due_by', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DISMISSED', 'Dismissed'), ('DONE', 'Done')], default='OPEN', max_length=12)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_ai_signals', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_ai_signals', to='stores.store')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_signals', to='commercial.commercialopportunity')),
            ],
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='commercial.commercialopportunity'),
        ),
        migrations.CreateModel(
            name='CommercialOpportunityStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_stage', models.CharField(blank=True, choices=[('PROSPECT', 'Prospect'), ('CONTACTED', 'Contacted'), ('RDV', 'Meeting'), ('QUOTE_SENT', 'Quote sent'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], default='', max_length=20)),
                ('to_stage', models.CharField(choices=[('PROSPECT', 'Prospect'), ('CONTACTED', 'Contacted'), ('RDV', 'Meeting'), ('QUOTE_SENT', 'Quote sent'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_stage_changes', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='commercial.commercialopportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommercialProspect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('DISQUALIFIED', 'Disqualified'), ('CONVERTED', 'Converted')], db_index=True, default='NEW', max_length=20)),
                ('estimated_potential', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_prospect_sources', to='customers.customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_prospects_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_prospects_owned', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='commercial.commercialleadsource')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_prospects', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='commercialopportunity',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='commercial.commercialprospect'),
        ),
        migrations.CreateModel(
            name='CommercialFollowUpTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='TODO', max_length=20)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_followup_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_followup_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_followup_tasks', to='stores.store')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_tasks', to='commercial.commercialopportunity')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_tasks', to='commercial.commercialprospect')),
            ],
            options={
                'ordering': ['status', 'due_at'],
            },
        ),
        migrations.AddField(
            model_name='commercialactivity',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='commercial.commercialprospect'),
        ),
        migrations.CreateModel(
            name='CommercialRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_regions', to='stores.enterprise')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='commercialprospect',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='commercial.commercialregion'),
        ),
        migrations.CreateModel(
            name='CommercialSector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_sectors', to='stores.enterprise')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='commercialprospect',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='commercial.commercialsector'),
        ),
        migrations.CreateModel(
            name='CommercialTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#0EA5E9', max_length=7)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_tags', to='stores.enterprise')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='commercialprospect',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='prospects', to='commercial.commercialtag'),
        ),
        migrations.AddField(
            model_name='commercialopportunity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='commercial.commercialtag'),
        ),
        migrations.CreateModel(
            name='CommercialTeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_team_memberships_as_manager', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_team_memberships_as_seller', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_team_memberships', to='stores.store')),
            ],
            options={
                'verbose_name': 'commercial team membership',
                'verbose_name_plural': 'commercial team memberships',
            },
        ),
        migrations.CreateModel(
            name='CommercialHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7)),
                ('score_overall', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('score_pipeline', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('score_activity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('score_conversion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('score_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('score_forecast', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('factors_json', models.JSONField(blank=True, default=dict)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_health_snapshots', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_health_snapshots', to='stores.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'seller', 'period'), name='uniq_commercial_health_snapshot')],
            },
        ),
        migrations.AddIndex(
            model_name='commercialincentivepolicy',
            index=models.Index(fields=['scope', 'is_active', 'effective_from'], name='commercial__scope_96684f_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialincentivepolicy',
            index=models.Index(fields=['store', 'is_active', 'effective_from'], name='commercial__store_i_19af80_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialincentiverun',
            index=models.Index(fields=['store', 'period', 'status'], name='commercial__store_i_e5484f_idx'),
        ),
        migrations.AddConstraint(
            model_name='commercialincentiverun',
            constraint=models.UniqueConstraint(fields=('store', 'period'), name='uniq_commercial_incentive_run'),
        ),
        migrations.AddConstraint(
            model_name='commercialincentiveresult',
            constraint=models.UniqueConstraint(fields=('run', 'seller'), name='uniq_commercial_incentive_result'),
        ),
        migrations.AddConstraint(
            model_name='commercialincentivetier',
            constraint=models.UniqueConstraint(fields=('policy', 'rank'), name='uniq_commercial_incentive_tier_rank'),
        ),
        migrations.AddConstraint(
            model_name='commercialleadsource',
            constraint=models.UniqueConstraint(fields=('enterprise', 'code'), name='uniq_commercial_lead_source_code'),
        ),
        migrations.AddIndex(
            model_name='commercialobjectivemonthly',
            index=models.Index(fields=['store', 'period'], name='commercial__store_i_e82423_idx'),
        ),
        migrations.AddConstraint(
            model_name='commercialobjectivemonthly',
            constraint=models.UniqueConstraint(fields=('store', 'seller', 'period'), name='uniq_commercial_objective_monthly'),
        ),
        migrations.AddIndex(
            model_name='commercialaisignal',
            index=models.Index(fields=['store', 'status', 'severity'], name='commercial__store_i_182c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialaisignal',
            index=models.Index(fields=['store', 'due_by'], name='commercial__store_i_18e209_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialopportunitystagehistory',
            index=models.Index(fields=['opportunity', 'created_at'], name='commercial__opportu_cb5ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialfollowuptask',
            index=models.Index(fields=['store', 'assigned_to', 'status', 'due_at'], name='commercial__store_i_239f10_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialfollowuptask',
            index=models.Index(fields=['store', 'status', 'due_at'], name='commercial__store_i_d5c5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialactivity',
            index=models.Index(fields=['store', 'actor', 'started_at'], name='commercial__store_i_a75556_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialactivity',
            index=models.Index(fields=['store', 'opportunity', 'started_at'], name='commercial__store_i_dabdb2_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialactivity',
            index=models.Index(fields=['store', 'next_action_at'], name='commercial__store_i_15dae9_idx'),
        ),
        migrations.AddConstraint(
            model_name='commercialregion',
            constraint=models.UniqueConstraint(fields=('enterprise', 'code'), name='uniq_commercial_region_code'),
        ),
        migrations.AddConstraint(
            model_name='commercialregion',
            constraint=models.UniqueConstraint(fields=('enterprise', 'name'), name='uniq_commercial_region_name'),
        ),
        migrations.AddConstraint(
            model_name='commercialsector',
            constraint=models.UniqueConstraint(fields=('enterprise', 'name'), name='uniq_commercial_sector_name'),
        ),
        migrations.AddConstraint(
            model_name='commercialtag',
            constraint=models.UniqueConstraint(fields=('enterprise', 'name'), name='uniq_commercial_tag_name'),
        ),
        migrations.AddIndex(
            model_name='commercialprospect',
            index=models.Index(fields=['store', 'status', 'owner'], name='commercial__store_i_561b54_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprospect',
            index=models.Index(fields=['store', 'next_follow_up_at'], name='commercial__store_i_8f0c21_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprospect',
            index=models.Index(fields=['store', 'last_activity_at'], name='commercial__store_i_2f1ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialopportunity',
            index=models.Index(fields=['store', 'stage', 'owner'], name='commercial__store_i_0281ec_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialopportunity',
            index=models.Index(fields=['store', 'owner', 'expected_close_date'], name='commercial__store_i_cda871_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialopportunity',
            index=models.Index(fields=['store', 'pipeline_order'], name='commercial__store_i_c552b7_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialteammembership',
            index=models.Index(fields=['store', 'manager', 'is_active'], name='commercial__store_i_c2a628_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialteammembership',
            index=models.Index(fields=['store', 'seller', 'is_active'], name='commercial__store_i_97ae8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='commercialteammembership',
            constraint=models.UniqueConstraint(fields=('store', 'manager', 'seller'), name='uniq_commercial_team_membership'),
        ),
    ]
