# Generated by Django 5.1.15 on 2026-03-07 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_method',
            field=models.CharField(choices=[('FACE', 'Reconnaissance faciale'), ('PIN', 'Code PIN'), ('QR', 'QR Code'), ('MANUAL', 'Manuel (manager)')], default='MANUAL', max_length=10, verbose_name='methode arrivee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_photo',
            field=models.ImageField(blank=True, upload_to='hrm/attendance/checkin/', verbose_name='photo arrivee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_method',
            field=models.CharField(blank=True, choices=[('FACE', 'Reconnaissance faciale'), ('PIN', 'Code PIN'), ('QR', 'QR Code'), ('MANUAL', 'Manuel (manager)')], default='', max_length=10, verbose_name='methode depart'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_photo',
            field=models.ImageField(blank=True, upload_to='hrm/attendance/checkout/', verbose_name='photo depart'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pin_code',
            field=models.CharField(blank=True, default='', help_text='Code PIN 4-6 chiffres pour pointage quand la reconnaissance faciale echoue.', max_length=6, verbose_name='code PIN pointage'),
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embeddings', models.JSONField(default=list, help_text='Liste de vecteurs (128 floats chacun) generes par face-api.js.', verbose_name='embeddings faciaux')),
                ('photo_1', models.ImageField(blank=True, upload_to='hrm/faces/', verbose_name='photo 1')),
                ('photo_2', models.ImageField(blank=True, upload_to='hrm/faces/', verbose_name='photo 2')),
                ('photo_3', models.ImageField(blank=True, upload_to='hrm/faces/', verbose_name='photo 3')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'enrolement")),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to='hrm.employee', verbose_name='employe')),
            ],
            options={
                'verbose_name': 'profil facial',
                'verbose_name_plural': 'profils faciaux',
            },
        ),
    ]
