# Generated by Django 5.1.15 on 2026-03-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_face_recognition_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Si renseigne, cette politique s'applique aux employes de ce departement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_policies', to='hrm.department', verbose_name='departement'),
        ),
    ]
