# Generated by Django 5.1.15 on 2026-03-07 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_add_department_to_attendancepolicy'),
        ('stores', '0022_add_enterprise_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifie'), ('CONFIRMED', 'Confirme'), ('ABSENT', 'Absent'), ('REPLACED', 'Remplace')], default='SCHEDULED', max_length=20, verbose_name='statut')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='hrm.employee', verbose_name='employe')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrm_schedule_entries', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'entree planning',
                'verbose_name_plural': 'entrees planning',
                'ordering': ['date', 'shift__start_time'],
            },
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, default='', verbose_name='raison')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='approuve par')),
                ('replacement_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements_as_substitute', to='hrm.employee', verbose_name='remplacant')),
                ('original_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='hrm.scheduleentry', verbose_name='entree originale')),
            ],
            options={
                'verbose_name': 'remplacement',
                'verbose_name_plural': 'remplacements',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrm_schedule_templates', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'modele de planning',
                'verbose_name_plural': 'modeles de planning',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('start_time', models.TimeField(verbose_name='heure debut')),
                ('end_time', models.TimeField(verbose_name='heure fin')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrm_shifts', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'creneau',
                'verbose_name_plural': 'creneaux',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplateLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(help_text='0=Lundi, 6=Dimanche', verbose_name='jour de la semaine')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.position', verbose_name='poste')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hrm.scheduletemplate', verbose_name='modele')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.shift', verbose_name='creneau')),
            ],
            options={
                'verbose_name': 'ligne de modele',
                'verbose_name_plural': 'lignes de modele',
                'ordering': ['day_of_week', 'shift__start_time'],
            },
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hrm.shift', verbose_name='creneau'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleentry',
            unique_together={('employee', 'date')},
        ),
    ]
