# Generated by Django 5.1.15 on 2026-02-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('SALES', 'Vendeur'), ('CASHIER', 'Caissier'), ('STOCKER', 'Magasinier')], db_index=True, default='SALES', max_length=20, verbose_name='role'),
        ),
    ]
