# Generated by Django 5.1.15 on 2026-02-17 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active_alter_user_role'),
        ('stores', '0011_add_invoice_fields_to_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('base_role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('SALES', 'Vendeur'), ('CASHIER', 'Caissier'), ('STOCKER', 'Magasinier')], default='SALES', max_length=20, verbose_name='niveau de permission')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='stores.enterprise', verbose_name='structure')),
            ],
            options={
                'verbose_name': 'Role personnalise',
                'verbose_name_plural': 'Roles personnalises',
                'ordering': ['name'],
                'unique_together': {('enterprise', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.customrole', verbose_name='role personnalise'),
        ),
    ]
