# Generated by Django 5.1.15 on 2026-02-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_custom_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrole',
            name='base_role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('HR', 'Ressources humaines'), ('COMMERCIAL', 'Commercial'), ('SALES', 'Vendeur'), ('CASHIER', 'Caissier'), ('STOCKER', 'Magasinier')], default='SALES', max_length=20, verbose_name='niveau de permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('HR', 'Ressources humaines'), ('COMMERCIAL', 'Commercial'), ('SALES', 'Vendeur'), ('CASHIER', 'Caissier'), ('STOCKER', 'Magasinier')], db_index=True, default='SALES', max_length=20, verbose_name='role'),
        ),
    ]
