# Generated by Django 5.2.11 on 2026-03-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customrole_base_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrole',
            name='base_role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('HR', 'Ressources humaines'), ('COMMERCIAL', 'Commercial'), ('SALES', 'Vendeur'), ('CASHIER', 'Caissier'), ('SALES_CASHIER', 'Vendeur Caissier'), ('STOCKER', 'Magasinier')], default='SALES', max_length=20, verbose_name='niveau de permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('HR', 'Ressources humaines'), ('COMMERCIAL', 'Commercial'), ('SALES', 'Vendeur'), ('CASHIER', 'Caissier'), ('SALES_CASHIER', 'Vendeur Caissier'), ('STOCKER', 'Magasinier')], db_index=True, default='SALES', max_length=20, verbose_name='role'),
        ),
    ]
