# Generated by Django 5.1.15 on 2026-02-15 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Stock faible'), ('OUT_OF_STOCK', 'Rupture de stock'), ('PENDING_PAYMENT_TIMEOUT', 'Paiement en attente (delai depasse)'), ('ABNORMAL_DISCOUNT', 'Remise anormale'), ('CASH_VARIANCE', 'Ecart de caisse'), ('CREDIT_OVERDUE', 'Credit en retard'), ('STOCK_RUPTURE_FORECAST', 'Prevision de rupture de stock')], max_length=30, verbose_name="type d'alerte")),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], default='INFO', max_length=10, verbose_name='severite')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Donnees JSON supplementaires (ex: product_id, sale_id, shift_id).', verbose_name='donnees supplementaires')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_alerts', to=settings.AUTH_USER_MODEL, verbose_name='lu par')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
            },
        ),
    ]
