# Generated by Django 5.1.15 on 2026-02-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Stock faible'), ('OUT_OF_STOCK', 'Rupture de stock'), ('PENDING_PAYMENT_TIMEOUT', 'Paiement en attente (delai depasse)'), ('ABNORMAL_DISCOUNT', 'Remise anormale'), ('CASH_VARIANCE', 'Ecart de caisse'), ('CREDIT_OVERDUE', 'Credit en retard'), ('STOCK_RUPTURE_FORECAST', 'Prevision de rupture de stock'), ('SELF_CHECKOUT', 'Auto-encaissement'), ('SUBSCRIPTION_EXPIRING', 'Abonnement bientot expire')], max_length=30, verbose_name="type d'alerte"),
        ),
    ]
