# Generated by Django 5.1.15 on 2026-03-09 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_add_subscription_expiring_alert_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Stock faible'), ('OUT_OF_STOCK', 'Rupture de stock'), ('PENDING_PAYMENT_TIMEOUT', 'Paiement en attente (delai depasse)'), ('ABNORMAL_DISCOUNT', 'Remise anormale'), ('CASH_VARIANCE', 'Ecart de caisse'), ('CREDIT_OVERDUE', 'Credit en retard'), ('STOCK_RUPTURE_FORECAST', 'Prevision de rupture de stock'), ('SELF_CHECKOUT', 'Auto-encaissement'), ('SUBSCRIPTION_EXPIRING', 'Abonnement bientot expire'), ('DELIVERY_LATE', 'Livraison en retard')], max_length=30, verbose_name="type d'alerte"),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.URLField(db_index=True, help_text='Push service endpoint URL.', max_length=500)),
                ('subscription_info', models.JSONField(help_text='PushSubscription JSON: {endpoint, keys: {p256dh, auth}}', verbose_name='subscription info')),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement push',
                'verbose_name_plural': 'Abonnements push',
                'constraints': [models.UniqueConstraint(fields=('user', 'endpoint'), name='unique_user_push_endpoint')],
            },
        ),
    ]
