# Generated by Django 5.1.15 on 2026-02-21 00:00

import decimal
import uuid
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0015_enterprise_subscription_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('type', models.CharField(choices=[('STOCK', 'Stock'), ('FIXED', 'Fixe'), ('VARIABLE', 'Variable')], default='VARIABLE', max_length=20, verbose_name='type')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='stores.enterprise', verbose_name='entreprise')),
                ('store', models.ForeignKey(blank=True, help_text="Laissez vide pour une categorie globale de l'entreprise.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'categorie de depense',
                'verbose_name_plural': 'categories de depenses',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('enterprise', 'store', 'name'), name='uniq_expense_category_per_scope')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('type', models.CharField(choices=[('CASH', 'Especes'), ('BANK', 'Banque'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20, verbose_name='type')),
                ('balance', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=14, verbose_name='solde')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('store', 'name'), name='uniq_wallet_name_per_store')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='numero de depense')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))], verbose_name='montant')),
                ('description', models.TextField(verbose_name='description')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255, verbose_name='fournisseur')),
                ('expense_date', models.DateField(db_index=True, verbose_name='date de depense')),
                ('status', models.CharField(choices=[('POSTED', 'Validee'), ('VOIDED', 'Annulee')], db_index=True, default='POSTED', max_length=10, verbose_name='statut')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='validee le')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='annulee le')),
                ('void_reason', models.TextField(blank=True, default='', verbose_name="motif d'annulation")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='categorie')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='cree par')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='stores.store', verbose_name='boutique')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_voided', to=settings.AUTH_USER_MODEL, verbose_name='annulee par')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'depense',
                'verbose_name_plural': 'depenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['store', 'status', 'expense_date'], name='expenses_ex_store_i_01d7a6_idx'), models.Index(fields=['store', 'created_at'], name='expenses_ex_store_i_d8410c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='Format YYYY-MM', max_length=7, verbose_name='periode')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='prochain numero')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_sequences', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'sequence depense',
                'verbose_name_plural': 'sequences depenses',
                'constraints': [models.UniqueConstraint(fields=('store', 'period'), name='uniq_expense_sequence_store_period')],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='Format YYYY-MM', max_length=7, verbose_name='periode')),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))], verbose_name='plafond')),
                ('alert_threshold_percent', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="seuil d'alerte (%)")),
                ('category', models.ForeignKey(blank=True, help_text='Laissez vide pour un budget global de la boutique.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to='expenses.expensecategory', verbose_name='categorie')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'budget depense',
                'verbose_name_plural': 'budgets depenses',
                'ordering': ['-period', 'category__name'],
                'constraints': [models.UniqueConstraint(fields=('store', 'category', 'period'), name='uniq_budget_store_category_period')],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))], verbose_name='montant')),
                ('description', models.TextField(verbose_name='description')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255, verbose_name='fournisseur')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuelle')], default='MONTHLY', max_length=10, verbose_name='frequence')),
                ('next_run_date', models.DateField(db_index=True, verbose_name='prochaine execution')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='derniere execution')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='expenses.expensecategory', verbose_name='categorie')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='cree par')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='stores.store', verbose_name='boutique')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='expenses.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'depense recurrente',
                'verbose_name_plural': 'depenses recurrentes',
                'ordering': ['next_run_date', 'created_at'],
                'indexes': [models.Index(fields=['store', 'is_active', 'next_run_date'], name='expenses_re_store_i_1301fd_idx')],
            },
        ),
    ]
