# Generated by Django 5.1.15 on 2026-03-07 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_alter_customer_email'),
        ('stores', '0022_add_enterprise_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=20, verbose_name='canal')),
                ('subject', models.CharField(blank=True, default='', max_length=200, verbose_name='sujet')),
                ('body', models.TextField(help_text='Placeholders: {{client_name}}, {{invoice_number}}, {{amount}}, {{store_name}}', verbose_name='contenu')),
                ('trigger_event', models.CharField(choices=[('MANUAL', 'Manuel'), ('SALE_COMPLETED', 'Vente payee'), ('PAYMENT_RECEIVED', 'Paiement recu'), ('CREDIT_DUE', 'Echeance credit'), ('DELIVERY_STATUS', 'Statut livraison')], default='MANUAL', max_length=30, verbose_name='evenement declencheur')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='stores.enterprise', verbose_name='entreprise')),
            ],
            options={
                'verbose_name': 'modele de message',
                'verbose_name_plural': 'modeles de message',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=20, verbose_name='canal')),
                ('recipient_contact', models.CharField(max_length=100, verbose_name='contact destinataire')),
                ('subject', models.CharField(blank=True, default='', max_length=200, verbose_name='sujet')),
                ('body_rendered', models.TextField(verbose_name='contenu rendu')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoye'), ('DELIVERED', 'Delivre'), ('FAILED', 'Echoue')], default='PENDING', max_length=20, verbose_name='statut')),
                ('error_message', models.TextField(blank=True, default='', verbose_name="message d'erreur")),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoye le')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='customers.customer', verbose_name='client')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='stores.store', verbose_name='boutique')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='communications.messagetemplate', verbose_name='modele')),
            ],
            options={
                'verbose_name': 'log de message',
                'verbose_name_plural': 'logs de messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('channel', models.CharField(max_length=20, verbose_name='canal')),
                ('segment_filter', models.JSONField(blank=True, default=dict, help_text='Ex: {"min_purchases": 3, "inactive_days": 30}', verbose_name='filtre de segment')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SCHEDULED', 'Programmee'), ('SENDING', "En cours d'envoi"), ('COMPLETED', 'Terminee'), ('CANCELLED', 'Annulee')], default='DRAFT', max_length=20, verbose_name='statut')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='programmee le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminee le')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='total destinataires')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='envoyes')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='echoues')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='stores.enterprise', verbose_name='entreprise')),
                ('store', models.ForeignKey(blank=True, help_text="Vide = toutes les boutiques de l'entreprise.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='stores.store', verbose_name='boutique')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='communications.messagetemplate', verbose_name='modele')),
            ],
            options={
                'verbose_name': 'campagne',
                'verbose_name_plural': 'campagnes',
                'ordering': ['-created_at'],
            },
        ),
    ]
