# Generated by Django 5.2.11 on 2026-03-10 20:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0023_store_receipt_custom_footer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(choices=[('ASSISTANT', 'Assistant IA'), ('NL_REPORT', 'Rapport langage naturel'), ('SMART_ENTRY', 'Saisie intelligente'), ('STOCK_PREDICTION', 'Prediction de stock'), ('CUSTOMER_ANALYSIS', 'Analyse client'), ('PRICE_RECO', 'Recommandation de prix'), ('ANOMALY', "Detection d'anomalies"), ('CREDIT_REMINDER', 'Relance credit')], default='ASSISTANT', max_length=20, verbose_name='fonctionnalite')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='titre')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archivee')], default='ACTIVE', max_length=10, verbose_name='statut')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadonnees')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='stores.store', verbose_name='boutique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'conversation IA',
                'verbose_name_plural': 'conversations IA',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant'), ('system', 'Systeme')], max_length=10, verbose_name='role')),
                ('content', models.TextField(verbose_name='contenu')),
                ('tool_calls', models.JSONField(blank=True, default=list, verbose_name='appels outils')),
                ('tool_results', models.JSONField(blank=True, default=list, verbose_name='resultats outils')),
                ('tokens_input', models.IntegerField(default=0, verbose_name='tokens entree')),
                ('tokens_output', models.IntegerField(default=0, verbose_name='tokens sortie')),
                ('model', models.CharField(blank=True, default='', max_length=60, verbose_name='modele')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='duree (ms)')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'message IA',
                'verbose_name_plural': 'messages IA',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIResponseCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(choices=[('ASSISTANT', 'Assistant IA'), ('NL_REPORT', 'Rapport langage naturel'), ('SMART_ENTRY', 'Saisie intelligente'), ('STOCK_PREDICTION', 'Prediction de stock'), ('CUSTOMER_ANALYSIS', 'Analyse client'), ('PRICE_RECO', 'Recommandation de prix'), ('ANOMALY', "Detection d'anomalies"), ('CREDIT_REMINDER', 'Relance credit')], max_length=20, verbose_name='fonctionnalite')),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='cle de cache')),
                ('response', models.TextField(verbose_name='reponse')),
                ('expires_at', models.DateTimeField(verbose_name='expiration')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_cache', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'cache reponse IA',
                'verbose_name_plural': 'cache reponses IA',
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(choices=[('ASSISTANT', 'Assistant IA'), ('NL_REPORT', 'Rapport langage naturel'), ('SMART_ENTRY', 'Saisie intelligente'), ('STOCK_PREDICTION', 'Prediction de stock'), ('CUSTOMER_ANALYSIS', 'Analyse client'), ('PRICE_RECO', 'Recommandation de prix'), ('ANOMALY', "Detection d'anomalies"), ('CREDIT_REMINDER', 'Relance credit')], max_length=20, verbose_name='fonctionnalite')),
                ('model', models.CharField(max_length=60, verbose_name='modele')),
                ('tokens_input', models.IntegerField(default=0, verbose_name='tokens entree')),
                ('tokens_output', models.IntegerField(default=0, verbose_name='tokens sortie')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10, verbose_name='cout estime (USD)')),
                ('cached', models.BooleanField(default=False, verbose_name='cache')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='stores.enterprise', verbose_name='entreprise')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='stores.store', verbose_name='boutique')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'log usage IA',
                'verbose_name_plural': 'logs usage IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
