# Generated by Django 5.1.15 on 2026-02-16
import uuid
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0008_store_enterprise_non_nullable"),
        ("catalog", "0002_add_enterprise_to_catalog"),
        ("credits", "0001_initial"),
        ("sales", "0001_initial"),
        ("cashier", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ABCAnalysis",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("quantity_sold", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("revenue", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("revenue_share", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=7)),
                ("cumulative_share", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=7)),
                ("abc_class", models.CharField(choices=[("A", "A"), ("B", "B"), ("C", "C")], db_index=True, max_length=1)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="abc_analyses", to="catalog.product"),
                ),
                (
                    "store",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="abc_analyses", to="stores.store"),
                ),
            ],
            options={
                "ordering": ["store", "abc_class", "-revenue"],
                "unique_together": {("store", "product", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="ReorderRecommendation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("computed_for", models.DateField(db_index=True)),
                ("avg_daily_sales", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=12)),
                ("lead_time_days", models.PositiveIntegerField(default=7)),
                ("safety_days", models.PositiveIntegerField(default=3)),
                ("reorder_point", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("current_available", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("suggested_order_qty", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("days_of_cover", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("urgency", models.CharField(choices=[("LOW", "Faible"), ("MEDIUM", "Moyenne"), ("HIGH", "Elevee")], db_index=True, default="LOW", max_length=10)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reorder_recommendations", to="catalog.product"),
                ),
                (
                    "store",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reorder_recommendations", to="stores.store"),
                ),
            ],
            options={
                "ordering": ["store", "-computed_for", "-suggested_order_qty"],
                "unique_together": {("store", "product", "computed_for")},
            },
        ),
        migrations.CreateModel(
            name="CustomerCreditScore",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("computed_for", models.DateField(db_index=True)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("grade", models.CharField(choices=[("A", "Excellent"), ("B", "Bon"), ("C", "Moyen"), ("D", "Risque"), ("E", "Critique")], db_index=True, max_length=1)),
                ("utilization_rate", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=7)),
                ("payment_ratio", models.DecimalField(decimal_places=4, default=Decimal("1.0000"), max_digits=7)),
                ("overdue_ratio", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=7)),
                ("overdue_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("balance", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("recommended_limit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="credit_scores", to="credits.customeraccount"),
                ),
                (
                    "customer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="credit_scores", to="customers.customer"),
                ),
                (
                    "store",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="credit_scores", to="stores.store"),
                ),
            ],
            options={
                "ordering": ["store", "-computed_for", "score"],
                "unique_together": {("store", "account", "computed_for")},
            },
        ),
        migrations.CreateModel(
            name="SalesForecast",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("forecast_date", models.DateField(db_index=True)),
                ("method", models.CharField(choices=[("MOVING_AVG", "Moyenne mobile")], default="MOVING_AVG", max_length=20)),
                ("predicted_qty", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("ma_7d", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=12)),
                ("ma_30d", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=12)),
                ("confidence", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=7)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_forecasts", to="catalog.product"),
                ),
                (
                    "store",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_forecasts", to="stores.store"),
                ),
            ],
            options={
                "ordering": ["store", "forecast_date", "-predicted_qty"],
                "unique_together": {("store", "product", "forecast_date", "method")},
            },
        ),
        migrations.CreateModel(
            name="FraudEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detected_on", models.DateField(db_index=True)),
                ("rule_code", models.CharField(db_index=True, max_length=60)),
                ("severity", models.CharField(choices=[("INFO", "Info"), ("WARNING", "Warning"), ("CRITICAL", "Critical")], db_index=True, default="INFO", max_length=10)),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fraud_events", to="cashier.payment"),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_fraud_events", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "sale",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fraud_events", to="sales.sale"),
                ),
                (
                    "store",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fraud_events", to="stores.store"),
                ),
            ],
            options={
                "ordering": ["-detected_on", "-risk_score", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="fraudevent",
            index=models.Index(fields=["store", "detected_on"], name="analytics_f_store_i_9475ae_idx"),
        ),
        migrations.AddIndex(
            model_name="fraudevent",
            index=models.Index(fields=["store", "is_resolved"], name="analytics_f_store_i_4c5b35_idx"),
        ),
        migrations.AddIndex(
            model_name="fraudevent",
            index=models.Index(fields=["store", "severity"], name="analytics_f_store_i_dfb6aa_idx"),
        ),
    ]
