# Generated by Django 5.1.15 on 2026-02-25 08:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('customers', '0004_customer_created_by'),
        ('stores', '0016_enterprisesubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalyticsRuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archive')], db_index=True, default='DRAFT', max_length=10)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('margin_proxy', models.JSONField(blank=True, default=dict)),
                ('dormant_days', models.PositiveSmallIntegerField(default=45)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_analytics_rulesets_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_analytics_rulesets', to='stores.store')),
            ],
            options={
                'ordering': ['store_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='CustomerIntelligenceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('DORMANT', 'Dormant'), ('CHURN', 'Risque churn'), ('CREDIT_RISK', 'Risque credit'), ('NEXT_ORDER', 'Prochaine commande')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Elevee'), ('CRITICAL', 'Critique')], db_index=True, default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('ACK', 'Accusee'), ('CLOSED', 'Fermee')], db_index=True, default='OPEN', max_length=10)),
                ('triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('assigned_seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customer_intelligence_alerts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_alerts', to='customers.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_intelligence_alerts', to='stores.store')),
            ],
            options={
                'ordering': ['-triggered_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMetricDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_date', models.DateField(db_index=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('paid_orders_count', models.PositiveIntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('credit_issued_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('credit_collected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('credit_overdue_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('strategic_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('profit_estimated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_metrics_daily', to='customers.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_metrics_daily', to='stores.store')),
            ],
            options={
                'ordering': ['store_id', '-metric_date', 'customer_id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMetricMonthly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.DateField(db_index=True, help_text='Premier jour du mois.')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('paid_orders_count', models.PositiveIntegerField(default=0)),
                ('active_weeks_count', models.PositiveIntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('strategic_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('profit_estimated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('credit_overdue_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('credit_overdue_count', models.PositiveIntegerField(default=0)),
                ('recovery_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('top_index', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_metrics_monthly', to='customers.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_metrics_monthly', to='stores.store')),
            ],
            options={
                'ordering': ['store_id', '-period_month', 'customer_id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerScoreSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_date', models.DateField(db_index=True)),
                ('period_type', models.CharField(choices=[('ROLLING_90D', 'Fenetre glissante 90 jours'), ('MONTHLY', 'Mensuel')], default='ROLLING_90D', max_length=20)),
                ('score_total', models.PositiveSmallIntegerField(default=0)),
                ('recency_score', models.PositiveSmallIntegerField(default=0)),
                ('frequency_score', models.PositiveSmallIntegerField(default=0)),
                ('monetary_score', models.PositiveSmallIntegerField(default=0)),
                ('credit_score', models.PositiveSmallIntegerField(default=0)),
                ('discount_behavior_score', models.PositiveSmallIntegerField(default=0)),
                ('segment', models.CharField(choices=[('VIP', 'VIP'), ('REGULAR', 'Regulier'), ('OCCASIONAL', 'Occasionnel'), ('DORMANT', 'Dormant'), ('RISK', 'Risque')], db_index=True, default='OCCASIONAL', max_length=20)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('explain', models.JSONField(blank=True, default=list)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_score_snapshots', to='customers.customer')),
                ('ruleset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_snapshots', to='analytics.customeranalyticsruleset')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_score_snapshots', to='stores.store')),
            ],
            options={
                'ordering': ['store_id', '-as_of_date', '-score_total'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSegmentSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_date', models.DateField(db_index=True)),
                ('segment', models.CharField(db_index=True, max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('strategy', models.JSONField(blank=True, default=list)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_segment_snapshots', to='customers.customer')),
                ('ruleset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_snapshots', to='analytics.customeranalyticsruleset')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_segment_snapshots', to='stores.store')),
            ],
            options={
                'ordering': ['store_id', '-as_of_date', 'customer_id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTopMonthly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.DateField(db_index=True, help_text='Premier jour du mois.')),
                ('rank', models.PositiveIntegerField()),
                ('top_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('badge', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='BRONZE', max_length=10)),
                ('explain', models.JSONField(blank=True, default=list)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_top_monthly', to='customers.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_top_monthly', to='stores.store')),
            ],
            options={
                'ordering': ['store_id', 'period_month', 'rank'],
            },
        ),
        migrations.AddIndex(
            model_name='customeranalyticsruleset',
            index=models.Index(fields=['store', 'status', '-effective_from'], name='analytics_c_store_i_80c672_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeranalyticsruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('store',), name='uniq_active_customer_ruleset_per_store'),
        ),
        migrations.AlterUniqueTogether(
            name='customeranalyticsruleset',
            unique_together={('store', 'version')},
        ),
        migrations.AddIndex(
            model_name='customerintelligencealert',
            index=models.Index(fields=['store', 'alert_type', 'status', 'triggered_at'], name='analytics_c_store_i_fc67d2_idx'),
        ),
        migrations.AddIndex(
            model_name='customermetricdaily',
            index=models.Index(fields=['store', 'metric_date'], name='analytics_c_store_i_5fd176_idx'),
        ),
        migrations.AddIndex(
            model_name='customermetricdaily',
            index=models.Index(fields=['store', 'customer', 'metric_date'], name='analytics_c_store_i_6033ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customermetricdaily',
            unique_together={('store', 'customer', 'metric_date')},
        ),
        migrations.AddIndex(
            model_name='customermetricmonthly',
            index=models.Index(fields=['store', 'period_month'], name='analytics_c_store_i_3611c4_idx'),
        ),
        migrations.AddIndex(
            model_name='customermetricmonthly',
            index=models.Index(fields=['store', 'customer', 'period_month'], name='analytics_c_store_i_876103_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customermetricmonthly',
            unique_together={('store', 'customer', 'period_month')},
        ),
        migrations.AddIndex(
            model_name='customerscoresnapshot',
            index=models.Index(fields=['store', 'as_of_date', '-score_total'], name='analytics_c_store_i_0f8b41_idx'),
        ),
        migrations.AddIndex(
            model_name='customerscoresnapshot',
            index=models.Index(fields=['store', 'segment', 'as_of_date'], name='analytics_c_store_i_330193_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerscoresnapshot',
            unique_together={('store', 'customer', 'as_of_date', 'period_type', 'ruleset')},
        ),
        migrations.AddIndex(
            model_name='customersegmentsnapshot',
            index=models.Index(fields=['store', 'segment', 'as_of_date'], name='analytics_c_store_i_0280fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customersegmentsnapshot',
            unique_together={('store', 'customer', 'as_of_date', 'ruleset')},
        ),
        migrations.AddIndex(
            model_name='customertopmonthly',
            index=models.Index(fields=['store', 'period_month', 'rank'], name='analytics_c_store_i_091ef6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customertopmonthly',
            unique_together={('store', 'period_month', 'customer'), ('store', 'period_month', 'rank')},
        ),
    ]
