# Generated by Django 5.1.15 on 2026-02-25 08:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_customeranalyticsruleset_customerintelligencealert_and_more'),
        ('customers', '0004_customer_created_by'),
        ('stores', '0016_enterprisesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecommendationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_date', models.DateField(db_index=True)),
                ('window_days', models.PositiveSmallIntegerField(default=90)),
                ('limit', models.PositiveSmallIntegerField(default=5)),
                ('include_only_in_stock', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_cache_entries', to='customers.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_recommendation_cache', to='stores.store')),
            ],
            options={
                'ordering': ['-generated_at', '-created_at'],
                'indexes': [models.Index(fields=['store', 'customer', 'as_of_date'], name='analytics_c_store_i_6c9649_idx'), models.Index(fields=['store', 'as_of_date', 'generated_at'], name='analytics_c_store_i_10ad43_idx')],
                'unique_together': {('store', 'customer', 'as_of_date', 'window_days', 'limit', 'include_only_in_stock')},
            },
        ),
    ]
