# Generated by Django 5.1.15 on 2026-02-23 21:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0016_enterprisesubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('FULL', 'Classement complet (noms visibles)'), ('TIER_AND_RANK', 'Palier + rang uniquement'), ('RANK_ONLY', 'Rang uniquement'), ('ANONYMOUS', 'Anonyme')], default='FULL', max_length=20, verbose_name='visibilite')),
                ('show_amounts', models.BooleanField(default=True, verbose_name='afficher les montants')),
                ('show_tier', models.BooleanField(default=True, verbose_name='afficher le palier')),
                ('refresh_interval_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='intervalle de raffraichissement (min)')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_settings', to='stores.store')),
            ],
            options={
                'verbose_name': 'parametres classement',
                'verbose_name_plural': 'parametres classements',
            },
        ),
        migrations.CreateModel(
            name='ObjectiveRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('valid_from', models.DateField(verbose_name='valide du')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="valide jusqu'au")),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_rules', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': "regle d'objectif",
                'verbose_name_plural': "regles d'objectif",
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='SellerMonthlyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7, verbose_name='periode (YYYY-MM)')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='encaissement brut')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='remboursements')),
                ('sale_count', models.PositiveIntegerField(default=0, verbose_name='nb ventes')),
                ('cancellation_count', models.PositiveIntegerField(default=0, verbose_name='nb annulations')),
                ('avg_basket', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='panier moyen')),
                ('credit_recovered', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='credit recouvre')),
                ('current_tier_rank', models.PositiveSmallIntegerField(default=0, verbose_name='rang palier')),
                ('current_tier_name', models.CharField(blank=True, max_length=60, verbose_name='nom palier')),
                ('bonus_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='bonus gagne')),
                ('tier_snapshot', models.JSONField(default=list, verbose_name='snapshot paliers')),
                ('is_final', models.BooleanField(default=False, verbose_name='cloture')),
                ('last_trigger', models.CharField(choices=[('PAYMENT', 'Paiement'), ('MANUAL', 'Manuel'), ('SCHEDULED', 'Planifie'), ('CLOSE', 'Cloture')], default='PAYMENT', max_length=20, verbose_name='dernier declencheur')),
                ('computed_at', models.DateTimeField(blank=True, null=True, verbose_name='calcule le')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_monthly_stats', to='stores.store')),
            ],
            options={
                'verbose_name': 'stats mensuelles vendeur',
                'verbose_name_plural': 'stats mensuelles vendeurs',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='SellerBonusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Verse'), ('CANCELLED', 'Annule')], default='PENDING', max_length=20, verbose_name='statut')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='verse le')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_payments_made', to=settings.AUTH_USER_MODEL)),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='objectives.sellermonthlystats')),
            ],
            options={
                'verbose_name': 'historique bonus',
                'verbose_name_plural': 'historique bonus',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7, verbose_name='periode (YYYY-MM)')),
                ('rule', models.ForeignKey(blank=True, help_text='Laissez vide pour utiliser la regle active de la boutique.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_objectives', to='objectives.objectiverule')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_objectives', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_objectives', to='stores.store')),
            ],
            options={
                'verbose_name': 'objectif vendeur',
                'verbose_name_plural': 'objectifs vendeurs',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='SellerPenaltyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('mode', models.CharField(choices=[('DEDUCTION', 'Deduction fixe'), ('HARD_CAP', 'Plafonnement de palier')], default='DEDUCTION', max_length=20, verbose_name='mode')),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='montant par defaut')),
                ('cap_tier_rank', models.PositiveSmallIntegerField(blank=True, help_text='Rang maximal autorise (mode HARD_CAP).', null=True, verbose_name='palier plafond')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_types', to='stores.store')),
            ],
            options={
                'verbose_name': 'type de penalite',
                'verbose_name_plural': 'types de penalites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SellerPenalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant deduction')),
                ('reason', models.TextField(blank=True, verbose_name='raison')),
                ('is_void', models.BooleanField(default=False, verbose_name='annulee')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='annulee le')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_penalties', to=settings.AUTH_USER_MODEL)),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='objectives.sellermonthlystats')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_penalties', to=settings.AUTH_USER_MODEL)),
                ('penalty_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='objectives.sellerpenaltytype')),
            ],
            options={
                'verbose_name': 'penalite',
                'verbose_name_plural': 'penalites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerSprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('starts_at', models.DateTimeField(verbose_name='debut')),
                ('ends_at', models.DateTimeField(verbose_name='fin')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'En cours'), ('FINISHED', 'Termine'), ('CANCELLED', 'Annule')], default='DRAFT', max_length=20, verbose_name='statut')),
                ('prize_description', models.TextField(blank=True, verbose_name='description du prix')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sprints', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='stores.store')),
            ],
            options={
                'verbose_name': 'sprint',
                'verbose_name_plural': 'sprints',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerSprintResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveSmallIntegerField(verbose_name='rang final')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='encaissement sprint')),
                ('is_winner', models.BooleanField(default=False, verbose_name='gagnant')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_results', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='objectives.sellersprint')),
            ],
            options={
                'verbose_name': 'resultat sprint',
                'verbose_name_plural': 'resultats sprint',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7, verbose_name='periode (YYYY-MM)')),
                ('data', models.JSONField(default=list, verbose_name='donnees classement')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='calcule le')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to='stores.store')),
            ],
            options={
                'verbose_name': 'snapshot classement',
                'verbose_name_plural': 'snapshots classement',
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('store', 'period'), name='uniq_leaderboard_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='ObjectiveTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='nom')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='rang')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='seuil (FCFA)')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='bonus (FCFA)')),
                ('bonus_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Taux applique si bonus_amount est 0.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='taux bonus (%)')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='couleur hex')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icone')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='objectives.objectiverule', verbose_name='regle')),
            ],
            options={
                'verbose_name': 'palier',
                'verbose_name_plural': 'paliers',
                'ordering': ['rank'],
                'constraints': [models.UniqueConstraint(fields=('rule', 'rank'), name='uniq_tier_rank_per_rule')],
            },
        ),
        migrations.CreateModel(
            name='SellerBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge_type', models.CharField(choices=[('BEST_MONTH', 'Meilleur mois'), ('SPRINT_WINNER', 'Gagnant de sprint'), ('MOST_IMPROVED', 'Plus grande progression'), ('TIER_ELITE', 'Palier Elite atteint'), ('CONSISTENCY', 'Regularite (3 mois consecutifs)'), ('PERFECT_MONTH', 'Mois parfait (0 penalite)'), ('CREDIT_CHAMPION', 'Champion recouvrement credit')], max_length=30, verbose_name='type')),
                ('period', models.CharField(max_length=7, verbose_name='periode (YYYY-MM)')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='libelle')),
                ('icon', models.CharField(default='trophy', max_length=50, verbose_name='icone')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='stores.store')),
            ],
            options={
                'verbose_name': 'badge',
                'verbose_name_plural': 'badges',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('seller', 'store', 'badge_type', 'period'), name='uniq_seller_badge_period')],
            },
        ),
        migrations.AddIndex(
            model_name='sellermonthlystats',
            index=models.Index(fields=['store', 'period'], name='objectives__store_i_4aaebf_idx'),
        ),
        migrations.AddIndex(
            model_name='sellermonthlystats',
            index=models.Index(fields=['seller', 'period'], name='objectives__seller__b4748e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellermonthlystats',
            constraint=models.UniqueConstraint(fields=('store', 'seller', 'period'), name='uniq_seller_monthly_stats'),
        ),
        migrations.AddConstraint(
            model_name='sellerobjective',
            constraint=models.UniqueConstraint(fields=('store', 'seller', 'period'), name='uniq_seller_objective_period'),
        ),
        migrations.AddConstraint(
            model_name='sellersprintresult',
            constraint=models.UniqueConstraint(fields=('sprint', 'seller'), name='uniq_sprint_result_seller'),
        ),
    ]
