# Generated by Django 5.2.11 on 2026-03-04 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
        ('stores', '0021_alter_enterprise_invoice_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectiverule',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objective_rules', to='stores.store', verbose_name='boutique'),
        ),
        migrations.AlterField(
            model_name='sellermonthlystats',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellermonthlystats',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_monthly_stats', to='stores.store'),
        ),
    ]
