# Generated by Django 5.2.11 on 2026-03-04 22:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0002_alter_objectiverule_store_and_more'),
        ('stores', '0021_alter_enterprise_invoice_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7, verbose_name='periode (YYYY-MM)')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='montant recompense')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('awarded_at', models.DateTimeField(blank=True, null=True, verbose_name='attribue le')),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_rewards_awarded', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rewards', to='stores.store')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_rewards_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recompense mensuelle',
                'verbose_name_plural': 'recompenses mensuelles',
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('store', 'period'), name='uniq_monthly_reward')],
            },
        ),
    ]
