# Generated by Django 5.2.11 on 2026-03-11 20:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_pricingpolicy_pricingrule_productvariant'),
        ('customers', '0006_customer_last_purchase_at_customer_loyalty_score_and_more'),
        ('sales', '0010_sale_offline_id'),
        ('stock', '0006_alter_productstock_unique_together_and_more'),
        ('stores', '0023_store_receipt_custom_footer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SAVDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.TextField(verbose_name='diagnostic')),
                ('probable_cause', models.TextField(blank=True, default='', verbose_name='cause probable')),
                ('proposed_solution', models.TextField(blank=True, default='', verbose_name='solution proposee')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cout estime')),
                ('estimated_days', models.PositiveIntegerField(default=1, verbose_name='delai estime (jours)')),
                ('is_repairable', models.BooleanField(default=True, verbose_name='reparable')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='technicien')),
            ],
            options={
                'verbose_name': 'diagnostic SAV',
                'verbose_name_plural': 'diagnostics SAV',
            },
        ),
        migrations.CreateModel(
            name='SAVDiagnosisPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantite')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cout unitaire')),
                ('in_stock', models.BooleanField(default=False, verbose_name='en stock')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_needed', to='sav.savdiagnosis', verbose_name='diagnostic')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_diagnosis_parts', to='catalog.product', verbose_name='produit catalogue')),
            ],
            options={
                'verbose_name': 'piece diagnostic',
                'verbose_name_plural': 'pieces diagnostic',
            },
        ),
        migrations.CreateModel(
            name='SAVQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='reference devis')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoye'), ('ACCEPTED', 'Accepte'), ('REFUSED', 'Refuse'), ('EXPIRED', 'Expire')], default='DRAFT', max_length=10, verbose_name='statut')),
                ('parts_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total pieces')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="main d'oeuvre")),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('valid_until', models.DateField(verbose_name="valide jusqu'au")),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepte le')),
                ('refused_at', models.DateTimeField(blank=True, null=True, verbose_name='refuse le')),
                ('client_notes', models.TextField(blank=True, default='', verbose_name='notes client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_quotes_created', to=settings.AUTH_USER_MODEL, verbose_name='cree par')),
            ],
            options={
                'verbose_name': 'devis SAV',
                'verbose_name_plural': 'devis SAV',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SAVQuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantite')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix unitaire')),
                ('line_type', models.CharField(choices=[('PART', 'Piece'), ('LABOR', "Main d'oeuvre"), ('OTHER', 'Autre')], default='PART', max_length=10, verbose_name='type')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sav.savquote', verbose_name='devis')),
            ],
            options={
                'verbose_name': 'ligne devis SAV',
                'verbose_name_plural': 'lignes devis SAV',
            },
        ),
        migrations.CreateModel(
            name='SAVTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='reference SAV')),
                ('status', models.CharField(choices=[('RECEIVED', 'Recu'), ('DIAGNOSING', 'En diagnostic'), ('AWAITING_CLIENT', 'Attente validation client'), ('IN_REPAIR', 'En reparation'), ('AWAITING_PART', 'En attente piece'), ('REPAIRED', 'Repare'), ('NOT_REPAIRABLE', 'Non reparable'), ('READY', 'Pret a restituer'), ('RETURNED', 'Restitue'), ('CLOSED', 'Cloture'), ('REFUSED', 'Refuse par client')], db_index=True, default='RECEIVED', max_length=20, verbose_name='statut')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10, verbose_name='priorite')),
                ('customer_name', models.CharField(max_length=150, verbose_name='nom client')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='telephone client')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email client')),
                ('brand_name', models.CharField(max_length=100, verbose_name='marque')),
                ('model_name', models.CharField(max_length=150, verbose_name='modele')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='numero de serie / IMEI')),
                ('product_condition', models.CharField(choices=[('GOOD', 'Bon etat'), ('SCRATCHED', 'Rayures'), ('DAMAGED', 'Endommage'), ('BROKEN', 'Casse')], default='GOOD', max_length=20, verbose_name='etat visuel')),
                ('warranty_status', models.CharField(choices=[('UNDER', 'Sous garantie'), ('OUT', 'Hors garantie'), ('UNKNOWN', 'A verifier')], default='UNKNOWN', max_length=10, verbose_name='statut garantie')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='fin de garantie')),
                ('declared_issue', models.TextField(verbose_name='panne declaree')),
                ('accessories', models.TextField(blank=True, default='', help_text='Chargeur, cable, boite, etc.', verbose_name='accessoires remis')),
                ('diagnosed_at', models.DateTimeField(blank=True, null=True, verbose_name='diagnostique le')),
                ('repair_started_at', models.DateTimeField(blank=True, null=True, verbose_name='reparation commencee le')),
                ('repaired_at', models.DateTimeField(blank=True, null=True, verbose_name='repare le')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='restitue le')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='cloture le')),
                ('return_code', models.CharField(blank=True, default='', max_length=6, verbose_name='code de restitution')),
                ('returned_to', models.CharField(blank=True, default='', max_length=150, verbose_name='restitue a')),
                ('return_notes', models.TextField(blank=True, default='', verbose_name='notes de restitution')),
                ('is_paid_repair', models.BooleanField(default=False, verbose_name='reparation payante')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cout total')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes internes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_tickets', to='customers.customer', verbose_name='client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_tickets', to='catalog.product', verbose_name='produit catalogue')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_received', to=settings.AUTH_USER_MODEL, verbose_name='recu par')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_tickets', to='sales.sale', verbose_name='vente/facture liee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sav_tickets', to='stores.store', verbose_name='boutique')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_assigned', to=settings.AUTH_USER_MODEL, verbose_name='technicien')),
            ],
            options={
                'verbose_name': 'dossier SAV',
                'verbose_name_plural': 'dossiers SAV',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SAVStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=20, verbose_name='ancien statut')),
                ('to_status', models.CharField(max_length=20, verbose_name='nouveau statut')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='raison')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='modifie par')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='sav.savticket', verbose_name='dossier SAV')),
            ],
            options={
                'verbose_name': 'historique statut SAV',
                'verbose_name_plural': 'historiques statut SAV',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SAVRepairAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='description')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='duree (minutes)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_repair_actions', to=settings.AUTH_USER_MODEL, verbose_name='technicien')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_actions', to='sav.savticket', verbose_name='dossier SAV')),
            ],
            options={
                'verbose_name': 'action reparation',
                'verbose_name_plural': 'actions reparation',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='savquote',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='sav.savticket', verbose_name='dossier SAV'),
        ),
        migrations.CreateModel(
            name='SAVPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='sav/photos/%Y/%m/', verbose_name='photo')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='legende')),
                ('phase', models.CharField(choices=[('RECEPTION', 'Reception'), ('DIAGNOSTIC', 'Diagnostic'), ('REPAIR', 'Reparation'), ('RETURN', 'Restitution')], default='RECEPTION', max_length=20, verbose_name='phase')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sav.savticket', verbose_name='dossier SAV')),
            ],
            options={
                'verbose_name': 'photo SAV',
                'verbose_name_plural': 'photos SAV',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SAVPartUsed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantite')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cout unitaire')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_parts', to='stock.inventorymovement', verbose_name='mouvement stock')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_parts_used', to='catalog.product', verbose_name='produit')),
                ('repair_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_used', to='sav.savrepairaction', verbose_name='action de reparation')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='sav.savticket', verbose_name='dossier SAV')),
            ],
            options={
                'verbose_name': 'piece utilisee SAV',
                'verbose_name_plural': 'pieces utilisees SAV',
            },
        ),
        migrations.AddField(
            model_name='savdiagnosis',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='sav.savticket', verbose_name='dossier SAV'),
        ),
    ]
