# Generated by Django 5.1.15 on 2026-02-15 04:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='plafond de credit')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Solde courant. Positif = le client doit de l'argent.", max_digits=14, verbose_name='solde')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to='customers.customer', verbose_name='client')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to='stores.store', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'compte credit',
                'verbose_name_plural': 'comptes credit',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('SALE_ON_CREDIT', 'Vente a credit'), ('CREDIT_PAYMENT', 'Paiement de credit'), ('ADJUSTMENT', 'Ajustement'), ('REFUND_TO_CREDIT', 'Remboursement en credit')], max_length=20, verbose_name="type d'ecriture")),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positif = augmente la dette, negatif = diminue la dette.', max_digits=14, verbose_name='montant')),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Solde du compte apres cette ecriture.', max_digits=14, verbose_name='solde apres')),
                ('reference', models.CharField(blank=True, default='', help_text='Ex: "Vente INV-0042" ou "Paiement REF-123".', max_length=200, verbose_name='reference')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='cree par')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_ledger_entries', to='sales.sale', verbose_name='vente')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='credits.customeraccount', verbose_name='compte')),
            ],
            options={
                'verbose_name': 'ecriture credit',
                'verbose_name_plural': 'ecritures credit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(verbose_name="date d'echeance")),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant du')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='montant paye')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PARTIAL', 'Partiellement paye'), ('PAID', 'Paye'), ('OVERDUE', 'En retard')], db_index=True, default='PENDING', max_length=10, verbose_name='statut')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='credits.customeraccount', verbose_name='compte')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_schedules', to='sales.sale', verbose_name='vente')),
            ],
            options={
                'verbose_name': 'echeancier',
                'verbose_name_plural': 'echeanciers',
                'ordering': ['due_date'],
            },
        ),
    ]
