# Generated by Django 5.1.15 on 2026-03-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditledgerentry',
            name='verification_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=16, verbose_name='hash de verification'),
        ),
        migrations.AddField(
            model_name='creditledgerentry',
            name='verification_token',
            field=models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True, verbose_name='jeton de verification'),
        ),
    ]
