# Generated by Django 5.2.11 on 2026-03-04 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_creditledgerentry_verification_hash_and_more'),
        ('customers', '0004_customer_created_by'),
        ('stores', '0021_alter_enterprise_invoice_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='credits.customeraccount', verbose_name='compte'),
        ),
        migrations.AlterField(
            model_name='creditledgerentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='cree par'),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_accounts', to='customers.customer', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_accounts', to='stores.store', verbose_name='boutique'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='credits.customeraccount', verbose_name='compte'),
        ),
    ]
